import { env } from "cloudflare:workers";
import { NextRequest, NextResponse } from "next/server";
import { getChatGPTUser, type ChatGPTUser } from "@/app/chatgpt-auth";
import { encryptSecret, publicationIssues, redactSecrets, validatePublicBaseUrl } from "@/lib/security";

type Ctx={params:Promise<{path:string[]}>};
type SkillStep={id?:string;name:string;type:string;prompt:string;source?:string;enabled?:boolean;modelAdapterId?:string};
const allowedStepTypes=new Set(["enhance","image_edit","image_generate","vision","listing_text","dataset","pricing","export"]);
const json=(data:unknown,status=200)=>NextResponse.json(data,{status});
const ok=(data:unknown,status=200)=>json({ok:true,data},status);
const fail=(error:string,status=400,code="REQUEST_FAILED")=>json({ok:false,error,code},status);
const now=()=>new Date().toISOString();
const id=()=>crypto.randomUUID();
const db=()=>{if(!env.DB)throw new Error("数据服务暂不可用");return env.DB};
const bucket=()=>{if(!env.BUCKET)throw new Error("文件服务暂不可用");return env.BUCKET};
const clean=(v:unknown,max=200)=>String(v??"").trim().slice(0,max);
async function body(req:NextRequest){const n=Number(req.headers.get("content-length")||0);if(n>512_000)throw new Error("请求内容过大");return req.json().catch(()=>{throw new Error("请求格式不是有效 JSON")}) as Promise<Record<string,unknown>>;}
async function currentUser(){const user=await getChatGPTUser();if(!user)throw Object.assign(new Error("请先登录后继续"),{status:401});await ensureUser(user);return user;}
async function ensureUser(user:ChatGPTUser){const t=now();await db().batch([
 db().prepare("INSERT INTO users (id,email,created_at,updated_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,updated_at=excluded.updated_at").bind(user.userId,user.email,t,t),
 db().prepare("INSERT INTO profiles (user_id,display_name,bio,created_at,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET display_name=excluded.display_name,updated_at=excluded.updated_at").bind(user.userId,user.displayName,"",t,t)
]);}
async function sha(value:string|ArrayBuffer){const data=typeof value==="string"?new TextEncoder().encode(value):value;return [...new Uint8Array(await crypto.subtle.digest("SHA-256",data))].map(x=>x.toString(16).padStart(2,"0")).join("");}
function parseDefinition(raw:unknown){if(!raw||typeof raw!=="object")throw new Error("Skill 定义不能为空");const x=raw as Record<string,unknown>;if(!Array.isArray(x.steps)||x.steps.length<1||x.steps.length>30)throw new Error("Skill 需要 1–30 个步骤");const steps=x.steps.map((s,i)=>{const p=s as Partial<SkillStep>;const type=clean(p.type||"listing_text",40);if(!allowedStepTypes.has(type))throw new Error(`第 ${i+1} 步类型无效`);const name=clean(p.name,100),prompt=clean(p.prompt,12000);if(!name)throw new Error(`第 ${i+1} 步缺少名称`);return {id:clean(p.id,80)||id(),name,type,prompt,source:clean(p.source||"previous",40),enabled:p.enabled!==false,modelAdapterId:clean(p.modelAdapterId,80)||undefined};});return {...x,steps};}
async function ownSkill(skillId:string,userId:string){return db().prepare("SELECT * FROM skills WHERE id=? AND owner_id=?").bind(skillId,userId).first<Record<string,unknown>>();}
async function ownProject(projectId:string,userId:string){return db().prepare("SELECT * FROM projects WHERE id=? AND owner_id=?").bind(projectId,userId).first<Record<string,unknown>>();}

function isPrivateAddress(value:string){const h=value.replace(/^\[|\]$/g,"").toLowerCase();if(h==="::1"||h==="0:0:0:0:0:0:0:1"||h.startsWith("fc")||h.startsWith("fd")||/^fe[89ab]/.test(h))return true;const m=h.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/);if(!m)return false;const a=Number(m[1]),b=Number(m[2]);return a===0||a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)||a>=224;}
async function validateResolvedHost(baseUrl:string){const host=new URL(baseUrl).hostname.replace(/^\[|\]$/g,"");if(isPrivateAddress(host))throw new Error("不允许本机或私网地址");if(/^\d+\.\d+\.\d+\.\d+$/.test(host)||host.includes(":"))return;let found=false;for(const type of ["A","AAAA"]){const r=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(host)}&type=${type}`,{headers:{accept:"application/dns-json"},signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error("无法验证 Base URL 的 DNS");const data=await r.json() as {Answer?:Array<{type:number;data:string}>};for(const answer of data.Answer||[]){if(answer.type!==1&&answer.type!==28)continue;found=true;if(isPrivateAddress(answer.data))throw new Error("Base URL 解析到了私网地址");}}if(!found)throw new Error("Base URL 没有可用的公共 DNS 记录");}
function providerRequest(base:string,protocol:string,modelId:string,key:string):{url:string;headers:Record<string,string>}{if(protocol==="gemini")return {url:`${base}/models/${encodeURIComponent(modelId)}`,headers:{"x-goog-api-key":key}};if(protocol==="claude")return {url:`${base}/models?limit=1000`,headers:{"x-api-key":key,"anthropic-version":"2023-06-01"}};return {url:`${base}/models`,headers:{authorization:`Bearer ${key}`}};}
async function testModel(input:Record<string,unknown>){const baseUrl=validatePublicBaseUrl(clean(input.baseUrl,1000)),modelId=clean(input.modelId,200),apiKey=clean(input.apiKey,1000),protocol=clean(input.protocol||"openai",30);if(!modelId||!apiKey)throw new Error("请填写 Model ID 和 API Key");if(!["openai","gemini","claude"].includes(protocol))throw new Error("不支持的协议类型");await validateResolvedHost(baseUrl);const request=providerRequest(baseUrl,protocol,modelId,apiKey);const started=Date.now();const r=await fetch(request.url,{headers:request.headers,redirect:"manual",signal:AbortSignal.timeout(12000)});if(r.status>=300&&r.status<400)throw new Error("模型服务发生了不安全的重定向");const text=await r.text();if(text.length>1_000_000)throw new Error("模型响应体过大");if(!r.ok){let reason="";try{const parsed=JSON.parse(text);reason=clean(parsed?.error?.message||parsed?.message,180)}catch{}throw new Error(`连接失败（HTTP ${r.status}）${reason?`：${reason}`:""}`);}const lower=modelId.toLowerCase();const capabilities=["text"];if(/vision|gpt-4o|gemini|claude-3|claude-sonnet/.test(lower))capabilities.push("vision");if(/image|imagen|dall-e/.test(lower))capabilities.push("image_generate","image_edit");return {baseUrl,modelId,protocol,capabilities:[...new Set(capabilities)],latencyMs:Date.now()-started};}

export async function GET(req:NextRequest,{params}:Ctx){const {path}=await params;const route=path.join("/");try{
 if(route==="models/public"){const result=await db().prepare("SELECT id,provider,base_url AS baseUrl,model_id AS modelId,protocol,name,capabilities_json AS capabilitiesJson,verified_at AS verifiedAt FROM public_models ORDER BY verified_at DESC LIMIT 100").all();return ok(result.results);}
 if(route==="skills/public"){const result=await db().prepare("SELECT s.id,s.name,s.description,s.category,s.rating_avg AS ratingAvg,s.usage_count AS usageCount,s.updated_at AS updatedAt,p.display_name AS author FROM skills s LEFT JOIN profiles p ON p.user_id=s.owner_id WHERE s.status='published' ORDER BY s.updated_at DESC LIMIT 100").all();return ok(result.results);}
 const user=await currentUser();
 if(route==="me")return ok({id:user.userId,email:user.email,displayName:user.displayName});
 if(route==="skills"){const result=await db().prepare("SELECT id,name,description,category,status,current_version_id AS currentVersionId,rating_avg AS ratingAvg,usage_count AS usageCount,updated_at AS updatedAt FROM skills WHERE owner_id=? ORDER BY updated_at DESC").bind(user.userId).all();return ok(result.results);}
 if(route.match(/^skills\/[^/]+$/)){const skillId=path[1];const skill=await db().prepare("SELECT * FROM skills WHERE id=? AND (owner_id=? OR status='published')").bind(skillId,user.userId).first<Record<string,unknown>>();if(!skill)return fail("Skill 不存在",404);const version=skill.current_version_id?await db().prepare("SELECT version,definition_json AS definitionJson,created_at AS createdAt FROM skill_versions WHERE id=?").bind(skill.current_version_id).first<Record<string,unknown>>():null;return ok({skill,version:version?{...version,definition:JSON.parse(String(version.definitionJson))}:null});}
 if(route==="projects"){const result=await db().prepare("SELECT p.id,p.name,p.category,p.description,p.created_at AS createdAt,p.updated_at AS updatedAt,(SELECT COUNT(*) FROM assets a WHERE a.project_id=p.id AND a.deleted_at IS NULL) AS assetCount FROM projects p WHERE p.owner_id=? ORDER BY p.updated_at DESC").bind(user.userId).all();return ok(result.results);}
 if(route.match(/^projects\/[^/]+$/)){const projectId=path[1];const project=await ownProject(projectId,user.userId);if(!project)return fail("项目不存在",404);const assets=await db().prepare("SELECT id,filename,mime,size,created_at AS createdAt FROM assets WHERE project_id=? AND owner_id=? AND deleted_at IS NULL ORDER BY created_at").bind(projectId,user.userId).all();return ok({project,assets:assets.results});}
 if(route==="models"){const result=await db().prepare("SELECT m.id,m.provider,m.name,m.base_url AS baseUrl,m.model_id AS modelId,m.protocol,m.capabilities_json AS capabilitiesJson,c.key_last4 AS keyLast4,m.updated_at AS updatedAt FROM model_adapters m LEFT JOIN user_model_credentials c ON c.adapter_id=m.id AND c.revoked_at IS NULL WHERE m.owner_id=? ORDER BY m.updated_at DESC").bind(user.userId).all();return ok(result.results);}
 if(route.match(/^assets\/[^/]+$/)){const assetId=path[1];const asset=await db().prepare("SELECT * FROM assets WHERE id=? AND owner_id=? AND deleted_at IS NULL").bind(assetId,user.userId).first<Record<string,unknown>>();if(!asset)return fail("文件不存在",404);const object=await bucket().get(String(asset.r2_key));if(!object)return fail("文件内容不存在",404);return new NextResponse(object.body,{headers:{"content-type":String(asset.mime),"content-disposition":`inline; filename*=UTF-8''${encodeURIComponent(String(asset.filename))}`,"cache-control":"private, max-age=300"}});}
 return fail("接口不存在",404);
 }catch(e){const status=Number((e as {status?:number}).status)||(/暂不可用/.test(String(e))?503:400);return fail(redactSecrets(e instanceof Error?e.message:"请求失败"),status,status===401?"UNAUTHORIZED":"REQUEST_FAILED");}}

export async function POST(req:NextRequest,{params}:Ctx){const {path}=await params;const route=path.join("/");try{
 if(route==="models/test"){await currentUser();return ok(await testModel(await body(req)));}
 const user=await currentUser();
 if(route==="models"){const input=await body(req);const tested=await testModel(input);if(!env.CREDENTIALS_MASTER_KEY)throw new Error("托管环境尚未配置加密主密钥，连接已验证但不能保存");const adapterId=id(),credentialId=id(),t=now(),provider=clean(input.provider||tested.protocol,80),name=clean(input.name||tested.modelId,120);const encrypted=await encryptSecret(clean(input.apiKey,1000),env.CREDENTIALS_MASTER_KEY);await db().batch([
 db().prepare("INSERT INTO model_adapters (id,owner_id,provider,name,base_url,model_id,protocol,mapping_json,capabilities_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(adapterId,user.userId,provider,name,tested.baseUrl,tested.modelId,tested.protocol,"{}",JSON.stringify(tested.capabilities),t,t),
 db().prepare("INSERT INTO user_model_credentials (id,owner_id,adapter_id,encrypted_key,key_last4,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(credentialId,user.userId,adapterId,encrypted,clean(input.apiKey,1000).slice(-4),t,t),
 db().prepare("INSERT INTO public_models (id,provider,base_url,model_id,protocol,name,capabilities_json,verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(provider,base_url,model_id,protocol) DO UPDATE SET name=excluded.name,capabilities_json=excluded.capabilities_json,verified_at=excluded.verified_at,updated_at=excluded.updated_at").bind(id(),provider,tested.baseUrl,tested.modelId,tested.protocol,name,JSON.stringify(tested.capabilities),t,t,t)
 ]);return ok({id:adapterId,keyLast4:clean(input.apiKey,1000).slice(-4),...tested},201);}
 if(route==="skills"){const input=await body(req),definition=parseDefinition(input.definition),skillId=id(),versionId=id(),t=now(),name=clean(input.name,120);if(!name)throw new Error("请填写 Skill 名称");const definitionJson=JSON.stringify(definition),checksum=await sha(definitionJson);const statements=[db().prepare("INSERT INTO skills (id,owner_id,name,description,category,status,current_version_id,rating_avg,usage_count,created_at,updated_at) VALUES (?,?,?,?,?,'draft',?,0,0,?,?)").bind(skillId,user.userId,name,clean(input.description,1000),clean(input.category||"Etsy 床品",100),versionId,t,t),db().prepare("INSERT INTO skill_versions (id,skill_id,version,definition_json,checksum,created_at) VALUES (?,?,?,?,?,?)").bind(versionId,skillId,1,definitionJson,checksum,t),...(definition.steps as SkillStep[]).map((step,index)=>db().prepare("INSERT INTO skill_steps (id,version_id,position,type,config_json) VALUES (?,?,?,?,?)").bind(id(),versionId,index,step.type,JSON.stringify(step)))];await db().batch(statements);return ok({id:skillId,version:1,status:"draft"},201);}
 if(route.match(/^skills\/[^/]+\/versions$/)){const skillId=path[1],skill=await ownSkill(skillId,user.userId);if(!skill)return fail("Skill 不存在",404);const input=await body(req),definition=parseDefinition(input.definition),last=await db().prepare("SELECT COALESCE(MAX(version),0) AS version FROM skill_versions WHERE skill_id=?").bind(skillId).first<{version:number}>(),version=Number(last?.version||0)+1,versionId=id(),t=now(),definitionJson=JSON.stringify(definition),checksum=await sha(definitionJson);const statements=[db().prepare("INSERT INTO skill_versions (id,skill_id,version,definition_json,checksum,created_at) VALUES (?,?,?,?,?,?)").bind(versionId,skillId,version,definitionJson,checksum,t),...(definition.steps as SkillStep[]).map((step,index)=>db().prepare("INSERT INTO skill_steps (id,version_id,position,type,config_json) VALUES (?,?,?,?,?)").bind(id(),versionId,index,step.type,JSON.stringify(step))),db().prepare("UPDATE skills SET name=?,description=?,category=?,current_version_id=?,updated_at=? WHERE id=? AND owner_id=?").bind(clean(input.name||skill.name,120),clean(input.description??skill.description,1000),clean(input.category||skill.category,100),versionId,t,skillId,user.userId)];await db().batch(statements);return ok({id:skillId,version,status:"draft"},201);}
 if(route.match(/^skills\/[^/]+\/publish$/)){const skillId=path[1],skill=await ownSkill(skillId,user.userId);if(!skill)return fail("Skill 不存在",404);const version=await db().prepare("SELECT definition_json FROM skill_versions WHERE id=?").bind(skill.current_version_id).first<{definition_json:string}>();const issues=publicationIssues(version?.definition_json||"");if(issues.length)return json({ok:false,error:"发布检查未通过",issues},422);await db().prepare("UPDATE skills SET status='published',updated_at=? WHERE id=? AND owner_id=?").bind(now(),skillId,user.userId).run();return ok({id:skillId,status:"published"});}
 if(route==="projects"){const input=await body(req),projectId=id(),t=now(),name=clean(input.name,120);if(!name)throw new Error("请填写商品名称");await db().prepare("INSERT INTO projects (id,owner_id,name,category,description,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(projectId,user.userId,name,clean(input.category,100),clean(input.description,3000),t,t).run();return ok({id:projectId,name,status:"draft"},201);}
 if(route.match(/^projects\/[^/]+\/assets$/)){const projectId=path[1],project=await ownProject(projectId,user.userId);if(!project)return fail("项目不存在",404);const form=await req.formData(),file=form.get("file");if(!(file instanceof File))throw new Error("请选择图片文件");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("仅支持 JPG、PNG 和 WebP");if(file.size<1||file.size>20*1024*1024)throw new Error("单张图片必须小于 20MB");const bytes=await file.arrayBuffer(),digest=await sha(bytes),existing=await db().prepare("SELECT id,filename FROM assets WHERE owner_id=? AND project_id=? AND sha256=? AND deleted_at IS NULL").bind(user.userId,projectId,digest).first<Record<string,unknown>>();if(existing)return ok({...existing,duplicate:true});const assetId=id(),safeName=file.name.replace(/[^\p{L}\p{N}._-]+/gu,"-").slice(-140)||"image",key=`users/${user.userId}/projects/${projectId}/${assetId}-${safeName}`,t=now();await bucket().put(key,bytes,{httpMetadata:{contentType:file.type},customMetadata:{ownerId:user.userId,projectId}});try{await db().prepare("INSERT INTO assets (id,owner_id,project_id,r2_key,filename,mime,size,sha256,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(assetId,user.userId,projectId,key,file.name,file.type,file.size,digest,t).run();}catch(e){await bucket().delete(key);throw e}await db().prepare("UPDATE projects SET updated_at=? WHERE id=? AND owner_id=?").bind(t,projectId,user.userId).run();return ok({id:assetId,filename:file.name,size:file.size,url:`/api/assets/${assetId}`},201);}
 return fail("接口不存在",404);
 }catch(e){const status=Number((e as {status?:number}).status)||(/暂不可用/.test(String(e))?503:400);return fail(redactSecrets(e instanceof Error?e.message:"请求失败"),status,status===401?"UNAUTHORIZED":"REQUEST_FAILED");}}

export async function DELETE(_:NextRequest,{params}:Ctx){const {path}=await params,route=path.join("/");try{const user=await currentUser();if(route.match(/^assets\/[^/]+$/)){const assetId=path[1],asset=await db().prepare("SELECT * FROM assets WHERE id=? AND owner_id=? AND deleted_at IS NULL").bind(assetId,user.userId).first<Record<string,unknown>>();if(!asset)return fail("文件不存在",404);await db().prepare("UPDATE assets SET deleted_at=? WHERE id=? AND owner_id=?").bind(now(),assetId,user.userId).run();await bucket().delete(String(asset.r2_key));return ok({id:assetId,status:"deleted"});}if(route.match(/^models\/[^/]+$/)){const modelId=path[1];await db().batch([db().prepare("DELETE FROM user_model_credentials WHERE adapter_id=? AND owner_id=?").bind(modelId,user.userId),db().prepare("DELETE FROM model_adapters WHERE id=? AND owner_id=?").bind(modelId,user.userId)]);return ok({id:modelId,status:"deleted"});}return fail("接口不存在",404);}catch(e){const status=Number((e as {status?:number}).status)||400;return fail(redactSecrets(e instanceof Error?e.message:"请求失败"),status);}}

export const PUT=POST;
