const { chromium }=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const auth={'oai-authenticated-user-id':'browser-user','oai-authenticated-user-email':'browser@example.com','oai-authenticated-user-full-name':'Browser%20User','oai-authenticated-user-full-name-encoding':'percent-encoded-utf-8'};
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},extraHTTPHeaders:auth,acceptDownloads:true});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8787/skills/new',{waitUntil:'domcontentloaded'});
 await page.getByLabel('Skill 名称').fill('浏览器回归 Skill');
 await page.getByLabel('步骤提示词').fill('第一步专用提示 {product_name}');
 await page.getByRole('button',{name:/2\.更换卧室场景背景/}).click();
 assert.notEqual(await page.getByLabel('步骤提示词').inputValue(),'第一步专用提示 {product_name}');
 await page.getByLabel('步骤提示词').fill('第二步独立提示');
 await page.getByRole('button',{name:/保存云端草稿|保存新版本/}).click();
 await page.getByText(/云端版本 v\d+ 已保存/).waitFor();
 await page.reload({waitUntil:'domcontentloaded'});await page.getByText(/已加载云端版本 v\d+/).waitFor();
 assert.equal(await page.getByLabel('Skill 名称').inputValue(),'浏览器回归 Skill');
 await page.goto('http://127.0.0.1:8787/workspace',{waitUntil:'domcontentloaded'});
 await page.getByLabel('商品名称').fill('浏览器回归商品');
 await page.getByLabel('商品描述与要求').fill('真实亚麻纹理，保持颜色准确。');
 await page.locator('input[type=file]').first().setInputFiles({name:'sku.png',mimeType:'image/png',buffer:Buffer.from([137,80,78,71,13,10,26,10])});
 await page.getByRole('button',{name:/保存项目与素材/}).click();
 await page.waitForURL(/\/projects\/[0-9a-f-]+$/);await page.getByRole('heading',{name:'浏览器回归商品'}).waitFor();
 await page.goto('http://127.0.0.1:8787/datasets',{waitUntil:'domcontentloaded'});
 await page.getByLabel('导入 Landrop CSV').setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from('listing_id,shop_name,sales,shop_age\n1,Shop,120,1 year\n1,Shop,120,1 year\n2,Other,,')});
 await page.getByRole('button',{name:'开始清洗'}).click();await page.getByText(/2 条有效记录/).waitFor();
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'下载 CSV'}).click();const dl=await pending;const stream=await dl.createReadStream();let csv='';for await(const chunk of stream)csv+=chunk.toString();assert.match(csv,/monthly_sales/);
 await page.goto('http://127.0.0.1:8787/settings/models',{waitUntil:'domcontentloaded'});await page.getByLabel('供应商').selectOption('custom');await page.getByLabel('自定义供应商名称').fill('Example Gateway');await page.getByLabel('请求协议').selectOption('openai');assert.equal(await page.getByLabel('自定义供应商名称').inputValue(),'Example Gateway');
 const blocked=await page.request.post('http://127.0.0.1:8787/api/models/test',{headers:{'content-type':'application/json'},data:{protocol:'openai',baseUrl:'https://127.0.0.1/v1',modelId:'x',apiKey:'secret-test'}});assert.equal(blocked.status(),400);assert.match((await blocked.json()).error,/私网/);
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8787/workspace',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'打开菜单'}).click();await page.getByRole('button',{name:'关闭菜单'}).waitFor();assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'关闭菜单');await page.keyboard.press('Escape');await page.getByRole('button',{name:'打开菜单'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false);
 assert.deepEqual(errors,[]);console.log('PASS: cloud Skill persistence, project upload, CSV export, custom provider UI, SSRF block, mobile navigation, no browser errors');
}finally{await browser.close()}
