"use client";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { api, signIn } from "@/lib/client-api";
import { toast } from "sonner";

type Step={id:string;name:string;type:string;prompt:string;source:string;enabled:boolean;modelAdapterId?:string};
type Model={id:string;name:string;modelId:string};
type SavedSkill={id:string;name:string;status:string;currentVersionId:string};
const types=[['enhance','商品图片保真清晰化'],['image_edit','图片编辑与背景更换'],['image_generate','文字生图'],['vision','图片视觉分析 / OCR'],['listing_text','标题、描述与标签'],['dataset','竞品数据清洗与统计'],['pricing','定价建议'],['export','Etsy 上架包导出']];
const starter:Step[]=[['商品图片保真清晰化','enhance'],['更换卧室场景背景','image_edit'],['视觉分析与属性提取','vision'],['标题、描述与标签','listing_text'],['定价建议','pricing'],['生成 Etsy 上架包','export']].map(([name,type],i)=>({id:`starter-${i+1}`,name,type,prompt:i===0?'保持 {product_name} 的颜色、织物纹理、比例、文字和构图真实。':'结合 {product_name}、{sku_attributes} 与上一步结果完成本步骤。',source:i?'previous':'original',enabled:true}));
export function CloudSkillEditor(){
 const [name,setName]=useState("床品 Etsy 完整上架流程"),[description,setDescription]=useState("从 SKU 原图到 Etsy 上架素材的完整床品流程"),[steps,setSteps]=useState<Step[]>(starter),[active,setActive]=useState(0),[models,setModels]=useState<Model[]>([]),[skillId,setSkillId]=useState(""),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[status,setStatus]=useState("尚未保存到云端");
 const step=steps[active];
 useEffect(()=>{Promise.all([api<SavedSkill[]>("/api/skills"),api<Model[]>("/api/models")]).then(async([skills,m])=>{setModels(m);const remembered=localStorage.getItem("loomlink:last-skill-id"),found=skills.find(s=>s.id===remembered)||skills[0];if(found){const detail=await api<{skill:Record<string,unknown>;version:{version:number;definition:{steps:Step[]}}}>(`/api/skills/${found.id}`);setSkillId(found.id);setName(String(detail.skill.name));setDescription(String(detail.skill.description||""));setSteps(detail.version.definition.steps);setVersion(detail.version.version);setStatus(`已加载云端版本 v${detail.version.version}`)}}).catch(e=>{if((e as {code?:string}).code!=="UNAUTHORIZED")setStatus((e as Error).message)})},[]);
 function update(values:Partial<Step>){setSteps(v=>v.map((s,i)=>i===active?{...s,...values}:s));setStatus("有未保存修改")}
 function move(direction:number){const next=active+direction;if(next<0||next>=steps.length)return;const copy=[...steps];[copy[active],copy[next]]=[copy[next],copy[active]];setSteps(copy);setActive(next);setStatus("有未保存修改")}
 async function save(){setBusy(true);try{const payload={name,description,category:"Etsy 床品",definition:{schemaVersion:1,steps}};const saved:{id?:string;version:number}=skillId?await api<{version:number}>(`/api/skills/${skillId}/versions`,{method:"POST",body:JSON.stringify(payload)}):await api<{id:string;version:number}>("/api/skills",{method:"POST",body:JSON.stringify(payload)});if(!skillId&&saved.id){setSkillId(saved.id);localStorage.setItem("loomlink:last-skill-id",saved.id)}setVersion(saved.version);setStatus(`云端版本 v${saved.version} 已保存`);toast.success("Skill 已保存到云端")}catch(e){const x=e as Error&{code?:string};if(x.code==="UNAUTHORIZED")signIn("/skills/new");else setStatus(x.message)}finally{setBusy(false)}}
 async function publish(){if(!skillId){setStatus("请先保存 Skill");return}if(!confirm("发布后其他用户可在 Skill 广场看到并使用当前版本，确认发布？"))return;setBusy(true);try{await api(`/api/skills/${skillId}/publish`,{method:"POST",body:"{}"});setStatus(`版本 v${version} 已发布`);toast.success("Skill 已通过检查并发布")}catch(e){const x=e as Error&{issues?:string[]};setStatus(x.issues?.join("；")||x.message)}finally{setBusy(false)}}
 return <div className="mx-auto max-w-[1450px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Skill Builder</p><h1 className="mt-2 text-3xl font-semibold">Skill 流程编辑器</h1><p className="mt-2 text-slate-300">每次保存创建不可变版本；发布前会检查密钥和私有地址。</p></div><div className="flex gap-2"><Button variant="outline" disabled={busy} onClick={save}>{busy?"保存中…":skillId?"保存新版本":"保存云端草稿"}</Button><Button disabled={busy||!skillId} onClick={publish}><ShieldCheck/>检查并发布</Button></div></div>
 <div className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-sm">Skill 名称<Input className="mt-2" value={name} onChange={e=>{setName(e.target.value);setStatus("有未保存修改")}}/></label><label className="text-sm">说明<Input className="mt-2" value={description} onChange={e=>{setDescription(e.target.value);setStatus("有未保存修改")}}/></label></div><p role="status" className="mt-3 text-sm text-slate-300">{status}</p>
 <div className="mt-5 grid gap-4 xl:grid-cols-[310px_1fr]"><section className="glass rounded-2xl p-4"><div className="space-y-2">{steps.map((s,i)=><button key={s.id} onClick={()=>setActive(i)} aria-pressed={active===i} className={`w-full rounded-xl p-3 text-left text-sm ${active===i?"bg-primary/20 ring-1 ring-primary/50":"bg-white/[.035] hover:bg-white/[.07]"}`}><span className="mr-2 text-slate-400">{i+1}.</span>{s.name}{!s.enabled&&<span className="ml-2 text-slate-400">停用</span>}</button>)}</div><Button className="mt-3 w-full" variant="outline" onClick={()=>{const next={id:crypto.randomUUID(),name:"新步骤",type:"listing_text",prompt:"",source:"previous",enabled:true};setSteps(v=>[...v,next]);setActive(steps.length);setStatus("有未保存修改")}}><Plus/>添加步骤</Button></section>
 <section className="glass rounded-2xl p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">步骤 {active+1}</h2><div className="flex gap-2"><Button size="icon-sm" variant="outline" aria-label="上移步骤" disabled={!active} onClick={()=>move(-1)}><ArrowUp/></Button><Button size="icon-sm" variant="outline" aria-label="下移步骤" disabled={active===steps.length-1} onClick={()=>move(1)}><ArrowDown/></Button><Button size="icon-sm" variant="outline" aria-label="删除步骤" disabled={steps.length===1} onClick={()=>{if(!confirm("删除当前步骤？"))return;setSteps(v=>v.filter((_,i)=>i!==active));setActive(Math.max(0,active-1));setStatus("有未保存修改")}}><Trash2/></Button></div></div>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">步骤名称<Input className="mt-2" value={step.name} onChange={e=>update({name:e.target.value})}/></label><label className="text-sm">步骤类型<select className="mt-2 h-10 w-full rounded-md border bg-[#0b111a] px-3" value={step.type} onChange={e=>update({type:e.target.value})}>{types.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="text-sm">输入来源<select className="mt-2 h-10 w-full rounded-md border bg-[#0b111a] px-3" value={step.source} onChange={e=>update({source:e.target.value})}><option value="original">SKU 原图</option><option value="previous">上一步输出</option><option value="reference">参考图</option></select></label><label className="text-sm">执行模型<select className="mt-2 h-10 w-full rounded-md border bg-[#0b111a] px-3" value={step.modelAdapterId||""} onChange={e=>update({modelAdapterId:e.target.value||undefined})}><option value="">运行时选择</option>{models.map(m=><option key={m.id} value={m.id}>{m.name} · {m.modelId}</option>)}</select></label></div>
 <label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={step.enabled} onChange={e=>update({enabled:e.target.checked})}/>启用此步骤</label><label className="mt-4 block text-sm">步骤提示词<Textarea className="mt-2 min-h-52" value={step.prompt} onChange={e=>update({prompt:e.target.value})}/></label><div className="mt-3 flex flex-wrap gap-2">{["product_name","product_category","sku_name","sku_attributes","previous_text","competitor_summary"].map(v=><Button size="sm" variant="outline" key={v} onClick={()=>update({prompt:step.prompt+` {${v}}`})}>{`{${v}}`}</Button>)}</div></section></div></div>;
}
