"use client";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { api, signIn } from "@/lib/client-api";
import { toast } from "sonner";

type Step={id:string;name:string;type:string;prompt:string;source:string;enabled:boolean;modelAdapterId?:string};
type Model={id:string;name:string;modelId:string};
type SavedSkill={id:string;name:string;status:string;currentVersionId:string};
const types=[['enhance','图生图 · 商品图片保真清晰化'],['image_edit','图生图 · 图片编辑与背景更换'],['image_generate','文字生图 · 新图片生成'],['vision','图生文 · 图片视觉分析 / OCR'],['listing_text','图生文 / 文生文 · 商品标题、详情与标签'],['dataset','数据处理 · 竞品清洗与统计'],['pricing','文本分析 · 定价建议'],['export','导出 · Etsy 上架包']];
const typeHelp:Record<string,string>={enhance:'读取商品原图并输出清晰化图片，保护颜色、纹理、文字和构图。',image_edit:'读取商品或上一步图片，输出更换背景后的商品图。',image_generate:'根据提示词生成新图片，不要求上传输入图。',vision:'读取 SKU 图片并输出材质、颜色、尺寸、图案、文字等视觉信息。',listing_text:'可直接读取 SKU 原图，也可接收视觉分析文字，生成标题、商品详情、标签和属性。',dataset:'清洗竞品数据并生成统计摘要。',pricing:'结合商品信息和竞品摘要给出建议价格、成本拆分与依据。',export:'整理已经确认的图片和文字，生成 Etsy 上架资料。'};
const starter:Step[]=[
 {id:'starter-1',name:'商品图片保真清晰化',type:'enhance',source:'original',enabled:true,prompt:'在不改变商品的前提下提升 {product_name} 图片清晰度。严格保持颜色、织物纹理、比例、文字、边缘和构图真实。'},
 {id:'starter-2',name:'更换卧室场景背景',type:'image_edit',source:'previous',enabled:true,prompt:'保留商品主体、颜色和纹理，将背景替换为自然、真实、适合 Etsy 的卧室场景，不出现人物和品牌标识。'},
 {id:'starter-3',name:'从 SKU 图片提取商品属性',type:'vision',source:'original',enabled:true,prompt:'分析这张 {product_name} SKU 图片。提取可见颜色、材质纹理、图案、结构、尺寸文字、包装信息和适用风格；不确定的信息标记为“需确认”，不要臆测。'},
 {id:'starter-4',name:'生成标题、商品详情与标签',type:'listing_text',source:'previous',enabled:true,prompt:'根据商品信息与视觉分析结果生成 Etsy 上架文案。商品：{product_name}；分类：{product_category}；用户要求：{product_description}；视觉分析：{previous_text}。输出英文标题、完整商品详情、13 个 Etsy 标签、材料、颜色、风格和需要卖家确认的信息。避免编造图片中无法确认的参数。'},
 {id:'starter-5',name:'定价建议',type:'pricing',source:'previous',enabled:true,prompt:'结合 {product_name}、{product_description}、已生成的商品信息和竞品摘要 {competitor_summary}，给出建议售价区间、成本拆分、促销空间和定价依据；明确标注需要人工确认的成本。'},
 {id:'starter-6',name:'生成 Etsy 上架包',type:'export',source:'previous',enabled:true,prompt:'整理已确认的商品图片、标题、商品详情、标签、属性和定价建议，生成 Etsy 上架资料。'},
];
export function CloudSkillEditor(){
 const [name,setName]=useState("床品 Etsy 完整上架流程"),[description,setDescription]=useState("从 SKU 原图到 Etsy 上架素材的完整床品流程"),[steps,setSteps]=useState<Step[]>(starter),[active,setActive]=useState(0),[models,setModels]=useState<Model[]>([]),[skillId,setSkillId]=useState(""),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[status,setStatus]=useState("尚未保存到云端");
 const step=steps[active];
 useEffect(()=>{Promise.all([api<SavedSkill[]>("/api/skills"),api<Model[]>("/api/models")]).then(async([skills,m])=>{setModels(m);const remembered=localStorage.getItem("loomlink:last-skill-id"),found=skills.find(s=>s.id===remembered)||skills[0];if(found){const detail=await api<{skill:Record<string,unknown>;version:{version:number;definition:{steps:Step[]}}}>(`/api/skills/${found.id}`);setSkillId(found.id);setName(String(detail.skill.name));setDescription(String(detail.skill.description||""));setSteps(detail.version.definition.steps);setVersion(detail.version.version);setStatus(`已加载云端版本 v${detail.version.version}`)}}).catch(e=>{if((e as {code?:string}).code!=="UNAUTHORIZED")setStatus((e as Error).message)})},[]);
 function update(values:Partial<Step>){setSteps(v=>v.map((s,i)=>i===active?{...s,...values}:s));setStatus("有未保存修改")}
 function move(direction:number){const next=active+direction;if(next<0||next>=steps.length)return;const copy=[...steps];[copy[active],copy[next]]=[copy[next],copy[active]];setSteps(copy);setActive(next);setStatus("有未保存修改")}
 async function save(){setBusy(true);try{const payload={name,description,category:"Etsy 床品",definition:{schemaVersion:1,steps}};const saved:{id?:string;version:number}=skillId?await api<{version:number}>(`/api/skills/${skillId}/versions`,{method:"POST",body:JSON.stringify(payload)}):await api<{id:string;version:number}>("/api/skills",{method:"POST",body:JSON.stringify(payload)});if(!skillId&&saved.id){setSkillId(saved.id);localStorage.setItem("loomlink:last-skill-id",saved.id)}setVersion(saved.version);setStatus(`云端版本 v${saved.version} 已保存`);toast.success("Skill 已保存到云端")}catch(e){const x=e as Error&{code?:string};if(x.code==="UNAUTHORIZED")signIn("/skills/new");else setStatus(x.message)}finally{setBusy(false)}}
 async function publish(){if(!skillId){setStatus("请先保存 Skill");return}if(!confirm("发布后其他用户可在 Skill 广场看到并使用当前版本，确认发布？"))return;setBusy(true);try{await api(`/api/skills/${skillId}/publish`,{method:"POST",body:"{}"});setStatus(`版本 v${version} 已发布`);toast.success("Skill 已通过检查并发布")}catch(e){const x=e as Error&{issues?:string[]};setStatus(x.issues?.join("；")||x.message)}finally{setBusy(false)}}
 return <div className="mx-auto max-w-[1450px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Skill Builder</p><h1 className="mt-2 text-3xl font-semibold">Skill 流程编辑器</h1><p className="mt-2 text-slate-300">每次保存创建不可变版本；发布前会检查密钥和私有地址。</p></div><div className="flex gap-2"><Button variant="outline" disabled={busy} onClick={save}>{busy?"保存中…":skillId?"保存新版本":"保存云端草稿"}</Button><Button disabled={busy||!skillId} onClick={publish}><ShieldCheck/>检查并发布</Button></div></div>
 <div className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-sm">Skill 名称<Input className="mt-2" value={name} onChange={e=>{setName(e.target.value);setStatus("有未保存修改")}}/></label><label className="text-sm">说明<Input className="mt-2" value={description} onChange={e=>{setDescription(e.target.value);setStatus("有未保存修改")}}/></label></div><p role="status" className="mt-3 text-sm text-slate-300">{status}</p>
 <div className="mt-5 grid gap-4 xl:grid-cols-[310px_1fr]"><section className="glass rounded-2xl p-4"><div className="space-y-2">{steps.map((s,i)=><button key={s.id} onClick={()=>setActive(i)} aria-pressed={active===i} className={`w-full rounded-xl p-3 text-left text-sm ${active===i?"bg-primary/20 ring-1 ring-primary/50":"bg-white/[.035] hover:bg-white/[.07]"}`}><span className="mr-2 text-slate-400">{i+1}.</span>{s.name}<span className="mt-1 block pl-5 text-xs text-slate-400">{s.type==='listing_text'&&s.source==='original'?'直接读取图片生成文字':s.type==='vision'?'图片 → 属性文字':s.type.includes('image')||s.type==='enhance'?'生成或编辑图片':'生成或处理文字/数据'}</span>{!s.enabled&&<span className="ml-5 text-xs text-slate-400">停用</span>}</button>)}</div><Button className="mt-3 w-full" variant="outline" onClick={()=>{const next={id:crypto.randomUUID(),name:"商品标题、详情与标签",type:"listing_text",prompt:"根据 SKU 图片或上一步分析结果，为 {product_name} 生成 Etsy 标题、完整商品详情、13 个标签和商品属性。",source:"original",enabled:true};setSteps(v=>[...v,next]);setActive(steps.length);setStatus("有未保存修改")}}><Plus/>添加步骤</Button></section>
 <section className="glass rounded-2xl p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">步骤 {active+1}</h2><div className="flex gap-2"><Button size="icon-sm" variant="outline" aria-label="上移步骤" disabled={!active} onClick={()=>move(-1)}><ArrowUp/></Button><Button size="icon-sm" variant="outline" aria-label="下移步骤" disabled={active===steps.length-1} onClick={()=>move(1)}><ArrowDown/></Button><Button size="icon-sm" variant="outline" aria-label="删除步骤" disabled={steps.length===1} onClick={()=>{if(!confirm("删除当前步骤？"))return;setSteps(v=>v.filter((_,i)=>i!==active));setActive(Math.max(0,active-1));setStatus("有未保存修改")}}><Trash2/></Button></div></div>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">步骤名称<Input className="mt-2" value={step.name} onChange={e=>update({name:e.target.value})}/></label><label className="text-sm">步骤类型<select className="mt-2 h-10 w-full rounded-md border bg-[#0b111a] px-3" value={step.type} onChange={e=>update({type:e.target.value})}>{types.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="text-sm">输入来源<select className="mt-2 h-10 w-full rounded-md border bg-[#0b111a] px-3" value={step.source} onChange={e=>update({source:e.target.value})}><option value="original">SKU 原图（用于直接图生文/图生图）</option><option value="previous">上一步输出（图片或文字）</option><option value="reference">参考图</option></select></label><label className="text-sm">执行模型<select className="mt-2 h-10 w-full rounded-md border bg-[#0b111a] px-3" value={step.modelAdapterId||""} onChange={e=>update({modelAdapterId:e.target.value||undefined})}><option value="">运行时选择</option>{models.map(m=><option key={m.id} value={m.id}>{m.name} · {m.modelId}</option>)}</select></label></div>
 <div className="mt-4 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-slate-200"><b>{step.type==='listing_text'&&step.source==='original'?'直接图生文：模型将同时接收 SKU 图片与提示词。':step.type==='listing_text'?'商品文案：模型将使用上一步视觉分析或文字结果。':types.find(x=>x[0]===step.type)?.[1]}</b><p className="mt-1 text-slate-300">{typeHelp[step.type]}</p></div>
 <label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={step.enabled} onChange={e=>update({enabled:e.target.checked})}/>启用此步骤</label><label className="mt-4 block text-sm">步骤提示词<Textarea className="mt-2 min-h-52" value={step.prompt} onChange={e=>update({prompt:e.target.value})}/></label><div className="mt-3 flex flex-wrap gap-2">{["product_name","product_category","product_description","sku_name","sku_attributes","previous_text","competitor_summary"].map(v=><Button size="sm" variant="outline" key={v} onClick={()=>update({prompt:step.prompt+` {${v}}`})}>{`{${v}}`}</Button>)}</div></section></div></div>;
}
