"use client";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { ArrowRight, Plus, Search, Star } from "lucide-react";
import { api } from "@/lib/client-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import type { StudioView } from "@/components/studio-app";

type Skill={id:string;name:string;description:string;category:string;author?:string;ratingAvg:number;usageCount:number;status?:string;updatedAt:string};
type Model={id:string;name:string;provider:string;baseUrl:string;modelId:string;protocol:string;capabilitiesJson:string;verifiedAt:string;source:"official"|"verified";description?:string};
const capabilityNames:Record<string,string>={text:"文字生成",vision:"图生文",image_generate:"图片生成",image_edit:"图片编辑"};
const stepLabels:Record<string,string>={enhance:"图生图 · 保真清晰化",image_edit:"图生图 · 图片编辑",image_generate:"文字生图",vision:"图生文 · 视觉分析",listing_text:"图生文 / 文生文 · 商品详情",dataset:"数据清洗",pricing:"定价建议",export:"Etsy 上架包"};
export function MarketplacePanel({view}:{view:StudioView}){const path=usePathname();const [skills,setSkills]=useState<Skill[]>([]),[models,setModels]=useState<Model[]>([]),[query,setQuery]=useState(""),[detail,setDetail]=useState<{skill:Record<string,unknown>;version:{version:number;definition:{steps:Array<{name:string;type:string}>}}}|null>(null),[error,setError]=useState("");
 useEffect(()=>{setQuery(new URLSearchParams(location.search).get("q")||"");if(view==="model-market")api<Model[]>("/api/models/public").then(setModels).catch(e=>setError((e as Error).message));else if(view==="skill-detail"){const id=path.split("/").pop();api<typeof detail>(`/api/skills/${id}`).then(x=>setDetail(x)).catch(e=>setError((e as Error).message))}else api<Skill[]>(view==="profile"?"/api/skills":"/api/skills/public").then(setSkills).catch(e=>setError((e as Error).message))},[view,path]);
 if(error)return <div className="mx-auto max-w-5xl rounded-xl bg-red-500/10 p-5 text-red-200" role="alert">{error}</div>;
 if(view==="skill-detail"){if(!detail)return <p role="status">正在读取 Skill…</p>;const s=detail.skill;return <div className="mx-auto max-w-5xl"><Badge>{String(s.status)}</Badge><h1 className="mt-4 text-3xl font-semibold">{String(s.name)}</h1><p className="mt-3 text-slate-300">{String(s.description||"")}</p><p className="mt-3 text-sm text-slate-300">版本 v{detail.version.version}</p><section className="glass mt-6 rounded-2xl p-5"><h2 className="font-semibold">流程步骤</h2><p className="mt-1 text-sm text-slate-300">Skill 可以混合生成商品图、从图片提取信息并生成商品详情。</p><ol className="mt-4 space-y-2">{detail.version.definition.steps.map((x,i)=><li className="rounded-xl bg-white/[.035] p-3" key={i}>{i+1}. {x.name}<span className="ml-2 text-sm text-slate-400">{stepLabels[x.type]||x.type}</span></li>)}</ol></section><Button className="mt-5" asChild><a href="/workspace">在商品项目中使用</a></Button></div>}
 if(view==="model-market"){const filteredModels=models.filter(m=>(m.name+m.provider+m.modelId+m.description).toLowerCase().includes(query.toLowerCase()));return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">模型广场</h1><p className="mt-2 text-slate-300">常用官方模型与用户验证模型目录。这里只保存公开信息，不包含任何 API Key。</p></div><Button asChild><a href="/settings/models"><Plus/>添加其他模型</a></Button></div><label className="relative mt-5 block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input aria-label="搜索模型" className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索供应商、模型名称或 Model ID"/></label><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filteredModels.map(m=>{let caps:string[]=[];try{caps=JSON.parse(m.capabilitiesJson)}catch{}const href=`/settings/models?provider=${encodeURIComponent(m.provider)}&protocol=${encodeURIComponent(m.protocol)}&baseUrl=${encodeURIComponent(m.baseUrl)}&modelId=${encodeURIComponent(m.modelId)}&name=${encodeURIComponent(m.name)}`;return <article key={m.id} className="glass flex min-h-64 flex-col rounded-2xl p-5"><div className="flex items-start justify-between gap-3"><Badge variant={m.source==="official"?"default":"secondary"}>{m.source==="official"?"官方目录":"用户验证"}</Badge><span className="text-xs text-slate-400">{m.provider}</span></div><h2 className="mt-4 font-semibold">{m.name}</h2><p className="mt-1 break-all text-sm text-primary">{m.modelId}</p><p className="mt-3 text-sm leading-6 text-slate-300">{m.description}</p><div className="mt-4 flex flex-wrap gap-2">{caps.map(x=><Badge key={x} variant="secondary">{capabilityNames[x]||x}</Badge>)}</div><Button className="mt-auto pt-4" variant="outline" asChild><a href={href}>配置此模型<ArrowRight/></a></Button></article>})}{!filteredModels.length&&<p className="rounded-xl border p-5">没有匹配的模型。</p>}</div></div>}
 const own=view==="profile";const filtered=skills.filter(s=>(s.name+s.description+s.category).toLowerCase().includes(query.toLowerCase()));return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">{own?"我的 Skill":"Skill 广场"}</h1><p className="mt-2 text-slate-300">{own?"管理自己的云端草稿和已发布版本。":"浏览用户已经发布的真实流程。"}</p></div><Button asChild><a href="/skills/new"><Plus/>创建 Skill</a></Button></div>{!own&&<label className="relative mt-5 block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input aria-label="搜索公开 Skill" className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="按名称、分类或说明搜索"/></label>}<div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(s=><a href={`/skills/${s.id}`} key={s.id} className="glass rounded-2xl p-5 transition hover:-translate-y-0.5 hover:border-primary/50"><Badge variant="secondary">{s.category}</Badge><h2 className="mt-4 font-semibold">{s.name}</h2><p className="mt-2 line-clamp-2 text-sm text-slate-300">{s.description||"暂无说明"}</p><div className="mt-5 flex justify-between text-sm text-slate-300"><span>{own?s.status:s.author||"LoomLink 用户"}</span><span className="flex items-center gap-1"><Star className="size-4"/>{Number(s.ratingAvg||0).toFixed(1)} · {s.usageCount||0}</span></div></a>)}{!filtered.length&&<p className="rounded-xl border p-5">{own?"还没有保存 Skill。":"暂时没有匹配的公开 Skill。"}</p>}</div></div>}
