"use client";
import {useEffect,useState} from "react";
import {ListRestart,ShieldCheck,Trash2} from "lucide-react";
import {api,signIn} from "@/lib/client-api";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {toast} from "sonner";
type Model={id:string;provider:string;name:string;baseUrl:string;modelId:string;protocol:string;capabilitiesJson:string;keyLast4:string};
type Provider="openai"|"gemini"|"claude"|"custom"; type Protocol=Provider;
type Mapping={modelsPath:string;modelsArrayPath:string;modelIdPath:string;authHeader:string;authPrefix:string;chatPath:string;textResponsePath:string};
type AvailableModel={id:string;name:string};
const defaults={openai:"https://api.openai.com/v1",gemini:"https://generativelanguage.googleapis.com/v1beta",claude:"https://api.anthropic.com/v1"};
const initial:Mapping={modelsPath:"/models",modelsArrayPath:"data",modelIdPath:"id",authHeader:"Authorization",authPrefix:"Bearer",chatPath:"/chat/completions",textResponsePath:"choices.0.message.content"};
const names={openai:"OpenAI",gemini:"Google",claude:"Anthropic"},select="mt-2 h-10 w-full rounded-md border bg-[#0b111a] px-3";
export function ModelSettings(){
 const [models,setModels]=useState<Model[]>([]),[preset,setPreset]=useState<Provider>("openai"),[customProvider,setCustomProvider]=useState(""),[protocol,setProtocol]=useState<Protocol>("openai"),[baseUrl,setBaseUrl]=useState(defaults.openai),[modelId,setModelId]=useState(""),[name,setName]=useState(""),[key,setKey]=useState(""),[mapping,setMapping]=useState(initial),[available,setAvailable]=useState<AvailableModel[]>([]),[manual,setManual]=useState(false),[tested,setTested]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const provider=preset==="custom"?customProvider.trim():names[preset as keyof typeof names],payload={protocol,provider,baseUrl,modelId,apiKey:key,mapping};
 const invalidate=()=>{setTested(false);setAvailable([])};
 async function load(){try{setModels(await api<Model[]>("/api/models"))}catch(e){if((e as {code?:string}).code!=="UNAUTHORIZED")setError((e as Error).message)}}
 useEffect(()=>{load();const q=new URLSearchParams(location.search),p=q.get("provider"),proto=q.get("protocol") as Protocol|null;if(!p||!proto)return;const known=p==="OpenAI"?"openai":p==="Google"?"gemini":p==="Anthropic"?"claude":"custom";setPreset(known);setCustomProvider(known==="custom"?p:"");setProtocol(proto);setBaseUrl(q.get("baseUrl")||"");setModelId(q.get("modelId")||"");setName(q.get("name")||"");setManual(true)},[]);
 async function discover(){if(!provider){setError("请填写自定义供应商名称");return}setBusy("discover");setError("");setTested(false);try{const r=await api<{models:AvailableModel[];latencyMs:number}>("/api/models/discover",{method:"POST",body:JSON.stringify(payload)});setAvailable(r.models);setManual(!r.models.length);if(r.models.length){const selected=r.models.find(x=>x.id===modelId)||r.models[0];setModelId(selected.id);setName(selected.name===selected.id?"":selected.name);setTested(true);toast.success(`检测成功，已获取 ${r.models.length} 个可用模型`)}else setError("连接检测成功，但接口没有返回模型列表。你可以手动填写模型 ID 和名称。")}catch(e){const x=e as Error&{code?:string};if(x.code==="UNAUTHORIZED")signIn("/settings/models");else setError(x.message)}finally{setBusy("")}}
 async function test(){if(!provider){setError("请填写自定义供应商名称");return}setBusy("test");setError("");try{const r=await api<{capabilities:string[];latencyMs:number}>("/api/models/test",{method:"POST",body:JSON.stringify(payload)});setTested(true);toast.success(`连接成功：${r.capabilities.join("、")} · ${r.latencyMs}ms`)}catch(e){setTested(false);setError((e as Error).message)}finally{setBusy("")}}
 async function save(){setBusy("save");setError("");try{await api("/api/models",{method:"POST",body:JSON.stringify({...payload,name:name||modelId})});toast.success("模型与加密密钥已保存");setKey("");setTested(false);setAvailable([]);await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 async function remove(id:string){if(!confirm("删除这个模型及其密钥？"))return;try{await api(`/api/models/${id}`,{method:"DELETE"});await load()}catch(e){setError((e as Error).message)}}
 const field=(k:keyof Mapping,title:string)=><label className="block text-xs text-slate-300">{title}<Input className="mt-1" value={mapping[k]} onChange={e=>{setMapping({...mapping,[k]:e.target.value});invalidate()}}/></label>;
 return <div className="mx-auto max-w-6xl"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Model Gateway</p><h1 className="mt-2 text-3xl font-semibold">模型与 API 密钥</h1><p className="mt-2 text-slate-300">输入 Base URL 和 API Key 后查询可用模型，检测通过再加密保存。</p></div>
 <div className="mt-7 grid gap-5 lg:grid-cols-[1fr_430px]"><section className="space-y-3">{models.length?models.map(m=><article key={m.id} className="glass flex items-center justify-between rounded-2xl p-4"><div><b>{m.name}</b><p className="mt-1 text-sm text-slate-300">{m.provider} · {m.modelId} · Key ····{m.keyLast4}</p></div><Button aria-label={`删除 ${m.name}`} variant="outline" size="icon" onClick={()=>remove(m.id)}><Trash2/></Button></article>):<div className="glass rounded-2xl p-6"><b>还没有保存模型</b><p className="mt-2 text-sm text-slate-300">在右侧查询并检测模型后保存。</p></div>}</section>
 <aside className="glass rounded-2xl p-5"><h2 className="font-semibold">添加模型</h2>
 <label className="mt-4 block text-sm">供应商<select aria-label="供应商" className={select} value={preset} onChange={e=>{const n=e.target.value as Provider;setPreset(n);invalidate();if(n!=="custom"){setProtocol(n);setBaseUrl(defaults[n])}}}><option value="openai">OpenAI</option><option value="gemini">Google</option><option value="claude">Anthropic</option><option value="custom">自定义供应商</option></select></label>
 {preset==="custom"&&<label className="mt-4 block text-sm">自定义供应商名称<Input aria-label="自定义供应商名称" className="mt-2" value={customProvider} onChange={e=>{setCustomProvider(e.target.value);setTested(false)}} placeholder="例如：OpenRouter、硅基流动或内部网关"/></label>}
 <label className="mt-4 block text-sm">请求协议<select aria-label="请求协议" className={select} value={protocol} onChange={e=>{const n=e.target.value as Protocol;setProtocol(n);invalidate();if(n!=="custom")setBaseUrl(defaults[n])}}><option value="openai">OpenAI 兼容</option><option value="gemini">Google Gemini</option><option value="claude">Anthropic Claude</option><option value="custom">声明式自定义协议</option></select></label>
 {protocol==="custom"&&<details className="mt-3 rounded-xl border border-white/10 p-3"><summary className="cursor-pointer text-sm font-medium">高级协议配置</summary><p className="mt-2 text-xs leading-5 text-slate-400">仅允许安全的路径和字段映射，不执行脚本。默认兼容 OpenAI JSON 结构。</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{field("modelsPath","模型列表路径")}{field("modelsArrayPath","模型数组字段")}{field("modelIdPath","模型 ID 字段")}{field("authHeader","鉴权 Header")}{field("authPrefix","鉴权前缀")}{field("chatPath","对话接口路径")}<div className="sm:col-span-2">{field("textResponsePath","文字响应字段")}</div></div></details>}
 <label className="mt-4 block text-sm">Base URL<Input aria-label="Base URL" className="mt-2" value={baseUrl} onChange={e=>{setBaseUrl(e.target.value);invalidate()}} placeholder="https://api.example.com/v1"/></label><label className="mt-4 block text-sm">API Key<Input aria-label="API Key" className="mt-2" type="password" autoComplete="new-password" value={key} onChange={e=>{setKey(e.target.value);invalidate()}} placeholder="只发送到本站服务端，不会公开"/></label>
 <Button className="mt-3 w-full" variant="outline" disabled={!!busy||!provider||!baseUrl||!key} onClick={discover}><ListRestart/>{busy==="discover"?"检测中…":"检测并获取可用模型"}</Button>
 {available.length>0&&!manual&&<><label className="mt-4 block text-sm">可用模型 <span className="text-xs text-slate-400">（{available.length} 个）</span><select aria-label="可用模型" className={select} value={modelId} onChange={e=>{const picked=available.find(x=>x.id===e.target.value)!;setModelId(picked.id);setName(picked.name===picked.id?"":picked.name)}}>{available.map(x=><option key={x.id} value={x.id}>{x.name===x.id?x.id:`${x.name} · ${x.id}`}</option>)}</select><button className="mt-2 text-xs text-primary" type="button" onClick={()=>setManual(true)}>列表中没有？手动填写</button></label><label className="mt-4 block text-sm">模型名称<Input aria-label="模型名称" className="mt-2" value={name} onChange={e=>setName(e.target.value)} placeholder="可修改显示名称"/></label></>}
 {manual&&<><label className="mt-4 block text-sm">Model ID<Input aria-label="Model ID" className="mt-2" value={modelId} onChange={e=>{setModelId(e.target.value);setTested(false)}} placeholder="供应商提供的模型 ID"/>{available.length>0&&<button className="mt-2 text-xs text-primary" type="button" onClick={()=>setManual(false)}>返回模型列表</button>}</label><label className="mt-4 block text-sm">模型名称<Input aria-label="模型名称" className="mt-2" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：DeepSeek Chat"/></label></>}
 {error&&<p role="alert" className="mt-4 rounded-lg bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<div className={`mt-5 grid gap-2 ${manual?"grid-cols-2":"grid-cols-1"}`}>{manual&&<Button variant="outline" disabled={!!busy||!provider||!baseUrl||!modelId||!key} onClick={test}><ShieldCheck/>{busy==="test"?"检测中…":"检测手填模型"}</Button>}<Button disabled={!!busy||!tested} onClick={save}>{busy==="save"?"保存中…":"保存所选模型"}</Button></div></aside></div></div>
}
