"use client";
import { useEffect, useState } from "react";
import { ShieldCheck, Trash2 } from "lucide-react";
import { api, signIn } from "@/lib/client-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

type Model={id:string;provider:string;name:string;baseUrl:string;modelId:string;protocol:string;capabilitiesJson:string;keyLast4:string};
const defaults={openai:"https://api.openai.com/v1",gemini:"https://generativelanguage.googleapis.com/v1beta",claude:"https://api.anthropic.com/v1"};
export function ModelSettings(){
 const [models,setModels]=useState<Model[]>([]),[protocol,setProtocol]=useState<keyof typeof defaults>("openai"),[baseUrl,setBaseUrl]=useState(defaults.openai),[modelId,setModelId]=useState(""),[name,setName]=useState(""),[key,setKey]=useState(""),[tested,setTested]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){try{setModels(await api<Model[]>("/api/models"))}catch(e){if((e as {code?:string}).code==="UNAUTHORIZED")return;setError((e as Error).message)}}
 useEffect(()=>{load()},[]);
 async function test(){setBusy(true);setError("");try{const r=await api<{capabilities:string[];latencyMs:number}>("/api/models/test",{method:"POST",body:JSON.stringify({protocol,baseUrl,modelId,apiKey:key})});setTested(true);toast.success(`连接成功：${r.capabilities.join("、")} · ${r.latencyMs}ms`)}catch(e){setTested(false);const x=e as Error&{code?:string};if(x.code==="UNAUTHORIZED")signIn("/settings/models");else setError(x.message)}finally{setBusy(false)}}
 async function save(){setBusy(true);setError("");try{await api("/api/models",{method:"POST",body:JSON.stringify({protocol,provider:protocol,name:name||modelId,baseUrl,modelId,apiKey:key})});toast.success("模型与加密密钥已保存");setKey("");setTested(false);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm("删除这个模型及其密钥？"))return;try{await api(`/api/models/${id}`,{method:"DELETE"});await load()}catch(e){setError((e as Error).message)}}
 return <div className="mx-auto max-w-6xl"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Model Gateway</p><h1 className="mt-2 text-3xl font-semibold">模型与 API 密钥</h1><p className="mt-2 text-slate-300">先进行真实连接检测，再把密钥加密保存。站内不会显示或导出完整密钥。</p></div>
 <div className="mt-7 grid gap-5 lg:grid-cols-[1fr_390px]"><section className="space-y-3">{models.length?models.map(m=><article key={m.id} className="glass flex items-center justify-between rounded-2xl p-4"><div><b>{m.name}</b><p className="mt-1 text-sm text-slate-300">{m.provider} · {m.modelId} · Key ····{m.keyLast4}</p></div><Button aria-label={`删除 ${m.name}`} variant="outline" size="icon" onClick={()=>remove(m.id)}><Trash2/></Button></article>):<div className="glass rounded-2xl p-6"><b>还没有保存模型</b><p className="mt-2 text-sm text-slate-300">在右侧填写供应商接口，检测成功后保存。</p></div>}</section>
 <aside className="glass rounded-2xl p-5"><h2 className="font-semibold">添加模型</h2><label className="mt-4 block text-sm">协议<select className="mt-2 h-10 w-full rounded-md border bg-[#0b111a] px-3" value={protocol} onChange={e=>{const p=e.target.value as keyof typeof defaults;setProtocol(p);setBaseUrl(defaults[p]);setTested(false)}}><option value="openai">OpenAI 兼容</option><option value="gemini">Google Gemini</option><option value="claude">Anthropic Claude</option></select></label><label className="mt-4 block text-sm">显示名称<Input className="mt-2" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：我的图像模型"/></label><label className="mt-4 block text-sm">Base URL<Input className="mt-2" value={baseUrl} onChange={e=>{setBaseUrl(e.target.value);setTested(false)}}/></label><label className="mt-4 block text-sm">Model ID<Input className="mt-2" value={modelId} onChange={e=>{setModelId(e.target.value);setTested(false)}} placeholder="供应商提供的模型 ID"/></label><label className="mt-4 block text-sm">API Key<Input className="mt-2" type="password" autoComplete="new-password" value={key} onChange={e=>{setKey(e.target.value);setTested(false)}} placeholder="仅发送到本站服务端"/></label>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<div className="mt-5 grid grid-cols-2 gap-2"><Button variant="outline" disabled={busy||!modelId||!key} onClick={test}><ShieldCheck/>{busy?"检测中…":"连接检测"}</Button><Button disabled={busy||!tested} onClick={save}>保存模型</Button></div></aside></div></div>;
}
