"use client";
import { useEffect, useState } from "react";
import { Download, ImagePlus, Trash2 } from "lucide-react";
import { usePathname } from "next/navigation";
import { api } from "@/lib/client-api";
import { Button } from "@/components/ui/button";

type Project={id:string;name:string;category:string;description:string;createdAt:string;assetCount:number};
type Asset={id:string;filename:string;mime:string;size:number};
function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function ProjectPanel(){const path=usePathname(),projectId=path.split("/").pop()||"demo";const [projects,setProjects]=useState<Project[]>([]),[detail,setDetail]=useState<{project:Project;assets:Asset[]}|null>(null),[error,setError]=useState("");
 useEffect(()=>{(projectId==="demo"?api<Project[]>("/api/projects").then(setProjects):api<{project:Project;assets:Asset[]}>(`/api/projects/${projectId}`).then(setDetail)).catch(e=>setError((e as Error).message))},[projectId]);
 async function remove(id:string){if(!confirm("删除这张素材？"))return;try{await api(`/api/assets/${id}`,{method:"DELETE"});setDetail(d=>d?{...d,assets:d.assets.filter(a=>a.id!==id)}:d)}catch(e){setError((e as Error).message)}}
 if(error)return <div role="alert" className="mx-auto max-w-4xl rounded-xl bg-red-500/10 p-5 text-red-200">{error}</div>;
 if(projectId==="demo")return <div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><h1 className="text-3xl font-semibold">商品项目</h1><p className="mt-2 text-slate-300">查看已保存的项目和 SKU 素材。</p></div><Button asChild><a href="/workspace"><ImagePlus/>新建项目</a></Button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{projects.map(p=><a href={`/projects/${p.id}`} key={p.id} className="glass rounded-2xl p-5 hover:border-primary/50"><h2 className="font-semibold">{p.name}</h2><p className="mt-2 text-sm text-slate-300">{p.category} · {p.assetCount} 张素材</p></a>)}{!projects.length&&<div className="glass rounded-2xl p-6"><b>还没有商品项目</b><p className="mt-2 text-sm text-slate-300">从工作台创建项目并上传第一组 SKU 图。</p></div>}</div></div>;
 if(!detail)return <p role="status">正在读取项目…</p>;const {project,assets}=detail;const csv='\uFEFF"filename","type","size"\r\n'+assets.map(a=>`"${a.filename.replace(/"/g,'""')}","${a.mime}","${a.size}"`).join('\r\n');return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">{project.name}</h1><p className="mt-2 text-slate-300">{project.category} · {assets.length} 张素材</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>download(`${project.name}-assets.csv`,csv,"text/csv;charset=utf-8")}><Download/>导出素材清单</Button><Button variant="outline" onClick={()=>download(`${project.name}.json`,JSON.stringify({project,assets},null,2),"application/json")}><Download/>导出 JSON</Button></div></div><p className="mt-4 max-w-3xl text-slate-300">{project.description}</p><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{assets.map(a=><figure key={a.id} className="glass overflow-hidden rounded-2xl"><img src={`/api/assets/${a.id}`} alt={a.filename} className="aspect-square w-full object-cover"/><figcaption className="flex items-center justify-between gap-2 p-3"><span className="truncate text-sm">{a.filename}</span><Button size="icon-sm" variant="outline" aria-label={`删除 ${a.filename}`} onClick={()=>remove(a.id)}><Trash2/></Button></figcaption></figure>)}</div>{!assets.length&&<p className="mt-6 rounded-xl border p-5">这个项目还没有素材。</p>}<section className="mt-8 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5"><h2 className="font-semibold">下一步：模型执行</h2><p className="mt-2 text-sm text-slate-300">项目和素材已经安全保存。逐步骤模型运行、结果确认和完整 Etsy ZIP 仍在接入中，本页不会伪造生成结果。</p><Button className="mt-4" disabled>开始执行 Skill（即将开放）</Button></section></div>}
