"use client";
import { DragEvent, useEffect, useMemo, useState } from "react";
import { ChevronRight, ImagePlus, Plus, Trash2, Upload } from "lucide-react";
import { api, signIn } from "@/lib/client-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";

type Skill={id:string;name:string;status:string};
const validTypes=new Set(["image/jpeg","image/png","image/webp"]);
export function ProjectWorkspace(){
 const [skills,setSkills]=useState<Skill[]>([]),[skillId,setSkillId]=useState(""),[name,setName]=useState(""),[category,setCategory]=useState("Bedding / Duvet cover"),[description,setDescription]=useState(""),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[dragging,setDragging]=useState(false),[error,setError]=useState("");
 useEffect(()=>{api<Skill[]>("/api/skills").then(s=>{setSkills(s);setSkillId(s[0]?.id||"")}).catch(()=>{})},[]);
 const previews=useMemo(()=>files.map(file=>({file,url:URL.createObjectURL(file)})),[files]);
 useEffect(()=>()=>previews.forEach(x=>URL.revokeObjectURL(x.url)),[previews]);
 function addFiles(list:File[]){setError("");const accepted=list.filter(f=>validTypes.has(f.type)&&f.size>0&&f.size<=20*1024*1024);if(accepted.length!==list.length)setError("已忽略非 JPG/PNG/WebP、空文件或超过 20MB 的文件");setFiles(old=>{const seen=new Set(old.map(f=>`${f.name}:${f.size}:${f.lastModified}`));return [...old,...accepted.filter(f=>!seen.has(`${f.name}:${f.size}:${f.lastModified}`))]})}
 function drop(e:DragEvent){e.preventDefault();setDragging(false);addFiles([...e.dataTransfer.files])}
 async function create(){if(!name.trim()||!files.length||!skillId){setError(!skillId?"请先创建并保存一个 Skill":"请填写商品名称并选择至少一张图片");return}setBusy(true);setError("");try{const project=await api<{id:string}>("/api/projects",{method:"POST",body:JSON.stringify({name,category,description})});for(let i=0;i<files.length;i++){const form=new FormData();form.append("file",files[i]);await api(`/api/projects/${project.id}/assets`,{method:"POST",body:form});setProgress(Math.round((i+1)/files.length*90))}await api("/api/runs",{method:"POST",body:JSON.stringify({projectId:project.id,skillId})});setProgress(100);toast.success("项目、素材与运行任务已创建");window.location.assign(`/projects/${project.id}`)}catch(e){const x=e as Error&{code?:string};if(x.code==="UNAUTHORIZED")signIn("/workspace");else setError(x.message)}finally{setBusy(false)}}
 return <div className="mx-auto max-w-[1450px]"><div className="mb-6"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">多模态商品工作台</p><h1 className="mt-2 text-3xl font-semibold">从 SKU 图片生成商品图与完整上架文案</h1><p className="mt-2 text-slate-300">一个 Skill 可同时包含图生图、文字生图、图生文、商品详情、标签、属性提取与定价步骤。上传原图后在项目页逐步确认结果。</p></div>
 <section className="glass rounded-2xl p-4 md:p-6"><div className="grid gap-6 lg:grid-cols-2"><div className="space-y-4"><label className="block text-sm">使用 Skill<select className="mt-2 h-11 w-full rounded-md border bg-[#0b111a] px-3" value={skillId} onChange={e=>setSkillId(e.target.value)}><option value="">选择云端 Skill</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name} · {s.status}</option>)}</select></label>{!skills.length&&<div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm"><p>还没有云端 Skill。</p><Button className="mt-3" size="sm" asChild><a href="/skills/new"><Plus/>先创建 Skill</a></Button></div>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">商品名称<Input className="mt-2" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：法式水洗亚麻被套"/></label><label className="text-sm">商品分类<Input className="mt-2" value={category} onChange={e=>setCategory(e.target.value)}/></label></div><label className="block text-sm">商品描述与要求<Textarea className="mt-2 min-h-36" value={description} onChange={e=>setDescription(e.target.value)} placeholder="材质、颜色、受众、风格和需要避免的内容"/></label></div>
 <div><label className="text-sm">SKU 图片</label><div onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={drop} className={`mt-2 flex min-h-56 flex-col items-center justify-center rounded-2xl border border-dashed p-6 text-center ${dragging?"border-primary bg-primary/10":"border-white/20 bg-black/20"}`}><Upload className="size-9 text-primary"/><b className="mt-3">拖入图片，或选择多张图片 / 文件夹</b><p className="mt-2 text-sm text-slate-300">JPG、PNG、WebP · 单张不超过 20MB</p><div className="mt-4 flex gap-2"><Button variant="outline" asChild><label className="cursor-pointer"><input className="hidden" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>addFiles([...e.target.files||[]])}/>选择图片</label></Button><Button variant="outline" asChild><label className="cursor-pointer"><input className="hidden" type="file" multiple accept="image/jpeg,image/png,image/webp" {...({webkitdirectory:""} as object)} onChange={e=>addFiles([...e.target.files||[]])}/>选择文件夹</label></Button></div></div>
 {previews.length>0&&<div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{previews.map(({file,url})=><figure key={`${file.name}:${file.lastModified}`} className="relative overflow-hidden rounded-xl border bg-black/20"><img src={url} alt={file.name} className="aspect-square w-full object-cover"/><figcaption className="truncate p-2 pr-10 text-xs">{file.name}</figcaption><Button className="absolute bottom-1 right-1" size="icon-sm" variant="outline" aria-label={`移除 ${file.name}`} onClick={()=>setFiles(v=>v.filter(x=>x!==file))}><Trash2/></Button></figure>)}</div>}</div></div>
 {error&&<p role="alert" className="mt-5 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}{busy&&<div className="mt-5"><div className="mb-2 flex justify-between text-sm"><span>正在保存项目和上传素材</span><span>{progress}%</span></div><Progress value={progress}/></div>}<div className="mt-6 flex justify-end"><Button size="lg" disabled={busy||!skills.length} onClick={create}>{busy?"正在上传…":"保存项目与素材"}<ChevronRight/></Button></div></section></div>;
}
