"use client";
import { useEffect, useState } from "react";
import { Download, ImagePlus, RefreshCw, Square, Trash2, WandSparkles } from "lucide-react";
import { usePathname } from "next/navigation";
import { api } from "@/lib/client-api";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

type Project={id:string;name:string;category:string;description:string;createdAt:string;assetCount:number};
type Asset={id:string;filename:string;mime:string;size:number};
type Run={id:string;status:string;currentStep:number;errorSafe?:string;createdAt:string};
type StepRun={id:string;runId:string;stepId:string;status:string;modelId?:string;outputJson?:string;durationMs?:number;errorSafe?:string};
type Detail={project:Project;assets:Asset[];runs:Run[];stepRuns:StepRun[]};
function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function ProjectPanel(){const path=usePathname(),projectId=path.split("/").pop()||"demo";const[projects,setProjects]=useState<Project[]>([]),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setError("");try{if(projectId==="demo")setProjects(await api<Project[]>("/api/projects"));else setDetail(await api<Detail>(`/api/projects/${projectId}`))}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[projectId]);
 async function remove(id:string){if(!confirm("删除这张素材？"))return;try{await api(`/api/assets/${id}`,{method:"DELETE"});await load()}catch(e){setError((e as Error).message)}}
 async function advance(runId:string){setBusy(true);setError("");try{await api(`/api/runs/${runId}/advance`,{method:"POST",body:"{}"});await load()}catch(e){setError((e as Error).message);await load()}finally{setBusy(false)}}
 async function retry(run:Run){setBusy(true);setError("");try{await api(`/api/runs/${run.id}/retry`,{method:"POST",body:JSON.stringify({stepIndex:run.currentStep})});await advance(run.id)}catch(e){setError((e as Error).message);setBusy(false)}}
 async function cancel(runId:string){if(!confirm("取消这个运行任务？已生成的结果会保留。"))return;setBusy(true);setError("");try{await api(`/api/runs/${runId}/cancel`,{method:"POST",body:"{}"});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(projectId==="demo")return <div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><h1 className="text-3xl font-semibold">商品项目</h1><p className="mt-2 text-slate-300">查看项目、SKU 素材和运行状态。</p></div><Button asChild><a href="/workspace"><ImagePlus/>新建项目</a></Button></div>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-500/10 p-4 text-red-200">{error}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2">{projects.map(p=><a href={`/projects/${p.id}`} key={p.id} className="glass rounded-2xl p-5 hover:border-primary/50"><h2 className="font-semibold">{p.name}</h2><p className="mt-2 text-sm text-slate-300">{p.category} · {p.assetCount} 张素材</p></a>)}{!projects.length&&!error&&<div className="glass rounded-2xl p-6"><b>还没有商品项目</b><p className="mt-2 text-sm text-slate-300">从工作台创建项目并上传第一组 SKU 图。</p></div>}</div></div>;
 if(!detail)return error?<div role="alert" className="rounded-xl bg-red-500/10 p-5 text-red-200">{error}</div>:<p role="status">正在读取项目…</p>;const{project,assets,runs,stepRuns}=detail,run=runs[0];const outputs=stepRuns.filter(x=>x.runId===run?.id);const csv='\uFEFF"filename","type","size"\r\n'+assets.map(a=>`"${a.filename.replace(/"/g,'""')}","${a.mime}","${a.size}"`).join('\r\n');
 return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">{project.name}</h1><p className="mt-2 text-slate-300">{project.category} · {assets.length} 张素材</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>download(`${project.name}-assets.csv`,csv,"text/csv;charset=utf-8")}><Download/>素材清单</Button><Button variant="outline" onClick={()=>download(`${project.name}.json`,JSON.stringify(detail,null,2),"application/json")}><Download/>项目 JSON</Button></div></div><p className="mt-4 max-w-3xl text-slate-300">{project.description}</p>
 {error&&<p role="alert" className="mt-5 rounded-xl bg-red-500/10 p-4 text-red-200">{error}</p>}<section className="glass mt-6 rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Skill 运行</h2><p className="mt-1 text-sm text-slate-300">每次只执行一个步骤；检查结果后再继续。</p></div>{run?<Badge variant="secondary">{run.status}{run.status!=="completed"&&run.status!=="cancelled"?` · 第 ${run.currentStep+1} 步`:""}</Badge>:<Badge variant="outline">未创建任务</Badge>}</div>{run&&<div className="mt-4 flex flex-wrap gap-2">{!['completed','cancelled'].includes(run.status)&&<Button disabled={busy||run.status==="running"} onClick={()=>advance(run.id)}><WandSparkles/>{busy?"调用模型中…":run.status==="awaiting_review"?"确认结果并执行下一步":"执行当前步骤"}</Button>}{run.status==="failed"&&<Button disabled={busy} variant="outline" onClick={()=>retry(run)}><RefreshCw/>重试失败步骤</Button>}{!['completed','cancelled'].includes(run.status)&&<Button disabled={busy} variant="outline" onClick={()=>cancel(run.id)}><Square/>取消任务</Button>}</div>}</section>
 {outputs.length>0&&<section className="mt-6 space-y-4"><h2 className="text-xl font-semibold">步骤结果</h2>{outputs.map((s,i)=>{let output:any={};try{output=JSON.parse(s.outputJson||"{}")}catch{}return <article key={s.id} className={`glass rounded-2xl p-5 ${s.status==="failed"?"border-red-500/30":""}`}><div className="flex justify-between gap-3"><b>步骤结果 {i+1}</b><span className="text-sm text-slate-300">{s.modelId} · {s.durationMs??0}ms</span></div>{output.text&&<pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-7 text-slate-200">{output.text}</pre>}{output.asset&&<img className="mt-4 max-h-[520px] rounded-xl object-contain" src={output.asset.url} alt={output.asset.filename}/>} {s.errorSafe&&<p className="mt-3 text-red-200">{s.errorSafe}</p>}</article>})}</section>}
 <section className="mt-8"><h2 className="text-xl font-semibold">项目素材</h2><div className="mt-4 grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{assets.map(a=><figure key={a.id} className="glass overflow-hidden rounded-2xl"><img src={`/api/assets/${a.id}`} alt={a.filename} className="aspect-square w-full object-cover"/><figcaption className="flex items-center justify-between gap-2 p-3"><span className="truncate text-sm">{a.filename}</span><Button size="icon-sm" variant="outline" aria-label={`删除 ${a.filename}`} onClick={()=>remove(a.id)}><Trash2/></Button></figcaption></figure>)}</div></section></div>}
