"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import {
  AppWindow, Boxes, ChartNoAxesCombined, ChevronRight, CircleUserRound,
  Database, Download, ImagePlus, Layers3, Library, Menu, Plus, Search,
  Settings2, ShieldCheck, Sparkles, Star, Upload, WandSparkles, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

export type StudioView = "workspace" | "skill-editor" | "skill-market" | "model-market" | "datasets" | "project" | "profile" | "models" | "skill-detail";

const nav = [
  ["/workspace", "工作台", AppWindow], ["/marketplace/skills", "Skill 广场", Library],
  ["/marketplace/models", "模型广场", Boxes], ["/datasets", "数据清洗", Database],
  ["/projects/demo", "商品项目", Layers3], ["/settings/models", "模型设置", Settings2],
] as const;

const skills = [
  { title: "床品场景图 · 轻法式卧室", author: "Mira Studio", rating: "4.9", runs: "2.8k", tag: "背景生成", color: "from-[#243d72] to-[#111b2e]" },
  { title: "商品图片保真清晰化", author: "LoomLink 官方", rating: "4.8", runs: "8.6k", tag: "官方", color: "from-[#28574f] to-[#102621]" },
  { title: "Etsy 标题与 13 标签", author: "NorthPeak", rating: "4.7", runs: "5.1k", tag: "文案", color: "from-[#593e76] to-[#21172d]" },
  { title: "Etsy 竞品数据清洗", author: "LoomLink 官方", rating: "4.9", runs: "3.2k", tag: "数据", color: "from-[#6a4928] to-[#271b11]" },
];

const steps = ["SKU 原图保真修复", "更换卧室场景背景", "视觉分析与属性提取", "标题、描述与标签", "定价建议", "生成 Etsy 上架包"];

function Brand() { return <Link href="/workspace" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary text-white shadow-[0_0_28px_#4d8dff55]"><Layers3 className="size-5"/></span><span><b className="block text-[15px] text-white">织链 LoomLink</b><small className="text-xs text-slate-500">Commerce Skill Studio</small></span></Link>; }

function Shell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const [mobile, setMobile] = useState(false);
  return <div className="min-h-screen bg-transparent text-slate-100">
    <aside className={`fixed inset-y-0 left-0 z-40 w-[248px] border-r border-white/8 bg-[#090d13]/95 px-4 py-5 backdrop-blur-xl transition-transform lg:translate-x-0 ${mobile ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center justify-between px-2"><Brand/><Button variant="ghost" size="icon-sm" className="lg:hidden" onClick={()=>setMobile(false)}><X/></Button></div>
      <nav className="mt-9 space-y-1">{nav.map(([href,label,Icon])=><Link key={href} href={href} onClick={()=>setMobile(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${path.startsWith(href.split("/demo")[0]) ? "bg-[#172234] text-white shadow-inner" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><Icon className="size-[18px]"/>{label}</Link>)}</nav>
      <div className="absolute inset-x-4 bottom-5 rounded-2xl border border-white/8 bg-white/[.025] p-3"><div className="flex items-center gap-2 text-xs text-slate-400"><ShieldCheck className="size-4 text-emerald-400"/>密钥已加密保护</div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full w-2/3 rounded-full bg-primary"/></div><p className="mt-2 text-[11px] text-slate-600">3 个模型可用 · 运行正常</p></div>
    </aside>
    <div className="lg:pl-[248px]"><header className="sticky top-0 z-30 flex h-16 items-center gap-4 border-b border-white/8 bg-[#080b10]/80 px-4 backdrop-blur-xl md:px-7"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></Button><div className="relative max-w-xl flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500"/><Input className="h-9 border-white/8 bg-white/[.035] pl-9" placeholder="搜索 Skill、模型或项目…"/></div><Badge variant="outline" className="hidden border-emerald-400/20 bg-emerald-400/5 text-emerald-300 sm:flex">系统正常</Badge><Link href="/profile/me" className="grid size-9 place-items-center rounded-full border border-white/10 bg-gradient-to-br from-[#2b4165] to-[#121a26]"><CircleUserRound className="size-5"/></Link></header>
      <main className="grid-fade min-h-[calc(100vh-4rem)] p-4 md:p-7">{children}</main>
    </div>
  </div>;
}

function Workspace() {
  const [files,setFiles]=useState<string[]>([]); const [running,setRunning]=useState(false); const [progress,setProgress]=useState(0);
  function run(){setRunning(true);setProgress(18);const timer=setInterval(()=>setProgress(v=>{if(v>=100){clearInterval(timer);setRunning(false);return 100}return v+17}),450)}
  return <div className="mx-auto max-w-[1480px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-primary">商品生成工作台</p><h1 className="text-2xl font-semibold tracking-tight md:text-3xl">把一组 SKU，变成完整上架包</h1></div><div className="flex gap-2"><Button variant="outline"><Download/>历史导出</Button><Button asChild><Link href="/skills/new"><Plus/>创建 Skill</Link></Button></div></div>
    <div className="grid gap-4 xl:grid-cols-[1fr_340px]"><section className="glass rounded-2xl p-4 md:p-6"><div className="grid gap-5 lg:grid-cols-[1fr_1.05fr]"><div><label className="text-sm font-medium">本次使用的 Skill</label><div className="mt-2 flex items-center justify-between rounded-xl border border-primary/30 bg-primary/5 p-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-primary/15 text-primary"><WandSparkles/></span><div><b className="text-sm">床品 Etsy 完整上架流程</b><p className="text-xs text-slate-500">6 步 · 图片 + 文案 + 定价</p></div></div><ChevronRight className="text-slate-500"/></div><div className="mt-5 grid grid-cols-2 gap-3"><Input placeholder="商品名称" defaultValue="法式水洗亚麻被套"/><Input placeholder="商品分类" defaultValue="Bedding / Duvet cover"/></div><textarea className="mt-3 min-h-28 w-full rounded-xl border border-input bg-black/20 p-3 text-sm outline-none focus:border-primary" defaultValue="天然亚麻触感，低饱和燕麦色。请保持织物纹理与颜色真实，生成适合 Etsy 的图片和英文文案。"/><div className="mt-3 flex items-center justify-between"><Button variant="ghost" size="sm"><Plus/>添加步骤要求</Button><span className="text-xs text-slate-600">自动保存草稿</span></div></div>
      <div><label className="text-sm font-medium">上传 SKU 图片</label><label className="mt-2 flex min-h-64 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-white/15 bg-black/20 p-6 text-center transition hover:border-primary/60 hover:bg-primary/[.035]"><input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>setFiles(Array.from(e.target.files||[]).map(f=>f.name))}/><span className="grid size-12 place-items-center rounded-2xl bg-white/5 text-primary"><Upload/></span><b className="mt-4 text-sm">拖入文件夹或选择多张图片</b><p className="mt-1 text-xs text-slate-500">JPG、PNG、WebP · 自动按文件名识别 SKU</p></label>{files.length>0&&<div className="mt-3 flex flex-wrap gap-2">{files.map(f=><Badge key={f} variant="secondary"><ImagePlus/>{f}</Badge>)}</div>}</div></div>
      <div className="mt-6 border-t border-white/8 pt-5">{running||progress===100?<div className="mb-4 rounded-xl border border-white/8 bg-white/[.025] p-3"><div className="mb-2 flex justify-between text-xs"><span>{running?"正在执行：SKU 原图保真修复":"流程已完成，可进入项目查看结果"}</span><b>{progress}%</b></div><Progress value={progress}/></div>:null}<div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-slate-500"><Sparkles className="size-4 text-primary"/>预计 18 次模型调用 · 使用你的 API Key</div><Button size="lg" onClick={run} disabled={running}>{running?"生成中…":"开始生成上架包"}<ChevronRight/></Button></div></div></section>
      <aside className="space-y-4"><div className="glass rounded-2xl p-4"><div className="flex items-center justify-between"><b className="text-sm">流程步骤</b><Badge variant="secondary">6 步</Badge></div><div className="mt-4 space-y-1">{steps.map((s,i)=><div key={s} className="flex items-center gap-3 rounded-xl p-2.5 hover:bg-white/[.035]"><span className={`grid size-7 place-items-center rounded-lg text-xs font-semibold ${i===0?"bg-primary text-white":"bg-white/5 text-slate-500"}`}>{i+1}</span><span className="text-sm text-slate-300">{s}</span></div>)}</div></div><div className="overflow-hidden rounded-2xl border border-white/8 bg-[#10151d]"><img className="h-40 w-full object-cover opacity-80" src="https://images.unsplash.com/photo-1582224163312-0735047647c6?auto=format&fit=crop&q=75&w=900" alt="自然光下的亚麻床品示例"/><div className="p-4"><p className="text-xs text-slate-500">风格参考</p><b className="mt-1 block text-sm">自然光 · 真实亚麻质感</b></div></div></aside></div></div>;
}

function SkillEditor(){
  const [active,setActive]=useState(1); const [saved,setSaved]=useState(false);
  return <div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Skill Builder</p><h1 className="mt-2 text-3xl font-semibold">床品 Etsy 完整上架流程</h1><p className="mt-2 text-sm text-slate-500">草稿 · v1 · 每次正式更新都会创建不可变版本</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setSaved(true)}>{saved?"已保存":"保存草稿"}</Button><Button><ShieldCheck/>检查并发布</Button></div></div>
  <div className="mt-6 grid gap-4 xl:grid-cols-[310px_1fr_320px]"><section className="glass rounded-2xl p-4"><div className="flex items-center justify-between"><b className="text-sm">流程步骤</b><Button size="icon-sm" variant="outline"><Plus/></Button></div><div className="mt-4 space-y-2">{steps.map((s,i)=><button key={s} onClick={()=>setActive(i)} className={`w-full rounded-xl border p-3 text-left transition ${active===i?"border-primary/40 bg-primary/10":"border-transparent bg-white/[.025] hover:bg-white/5"}`}><div className="flex items-center gap-3"><span className={`grid size-7 place-items-center rounded-lg text-xs ${active===i?"bg-primary text-white":"bg-white/5 text-slate-500"}`}>{i+1}</span><div><b className="block text-sm font-medium">{s}</b><small className="text-slate-600">{i<2?"图片编辑":"结构化输出"}</small></div></div></button>)}</div><Button variant="ghost" className="mt-3 w-full"><Plus/>添加步骤</Button></section>
  <section className="glass rounded-2xl p-5"><div className="flex items-center justify-between border-b border-white/8 pb-4"><div><b>步骤 {active+1} · {steps[active]}</b><p className="mt-1 text-xs text-slate-500">配置输入、模型、提示词和输出</p></div><Badge>已启用</Badge></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">步骤名称<Input className="mt-2" value={steps[active]} readOnly/></label><label className="text-sm">输入来源<select className="mt-2 h-9 w-full rounded-md border bg-black/20 px-3 text-sm"><option>上一步输出</option><option>SKU 原图</option><option>指定历史步骤</option></select></label><label className="text-sm">执行模型<select className="mt-2 h-9 w-full rounded-md border bg-black/20 px-3 text-sm"><option>Gemini 3 Pro Image</option><option>GPT Image 2</option><option>自动模型池</option></select></label><label className="text-sm">失败回退<select className="mt-2 h-9 w-full rounded-md border bg-black/20 px-3 text-sm"><option>GPT Image 2</option><option>不回退</option></select></label></div><label className="mt-5 block text-sm">通用提示词<Textarea className="mt-2 min-h-48 bg-black/20" defaultValue={`保持 {product_name} 的颜色、织物纹理、尺寸比例和所有可见细节不变。根据 {sku_attributes} 生成自然、可信的电商结果。禁止增加文字、水印或不存在的结构。`}/></label><div className="mt-3 flex flex-wrap gap-2">{["product_name","sku_name","sku_attributes","previous_text"].map(v=><Badge key={v} variant="outline">{`{${v}}`}</Badge>)}</div><div className="mt-5 flex justify-end gap-2"><Button variant="outline">单步试跑</Button><Button><WandSparkles/>试跑完整流程</Button></div></section>
  <aside className="space-y-4"><div className="glass rounded-2xl p-4"><b className="text-sm">输出设置</b><div className="mt-4 space-y-3 text-sm"><label className="block">格式<select className="mt-1 h-9 w-full rounded-md border bg-black/20 px-3"><option>JPEG</option><option>PNG</option><option>JSON</option></select></label><label className="block">尺寸<select className="mt-1 h-9 w-full rounded-md border bg-black/20 px-3"><option>2048 × 2048</option><option>原始比例</option></select></label><label className="block">超时<Input className="mt-1" defaultValue="180 秒"/></label></div></div><div className="rounded-2xl border border-amber-300/15 bg-amber-300/5 p-4 text-xs leading-5 text-amber-100/70">发布检查会扫描 API Key、私有地址、敏感信息和缺失资源。保存草稿不会自动公开。</div></aside></div></div>;
}

function ModelsPanel(){const [tested,setTested]=useState(false);return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Model Gateway</p><h1 className="mt-2 text-3xl font-semibold">模型与 API 密钥</h1><p className="mt-2 text-slate-400">密钥仅在服务端加密保存，前端不会再次显示明文。</p></div><Button><Plus/>添加模型</Button></div><div className="mt-7 grid gap-4 lg:grid-cols-[1fr_360px]"><section className="space-y-3">{[["GPT Image 2","OpenAI 兼容","图片生成 · 图片编辑"],["Gemini 3 Pro Image","Google Gemini","视觉 · 图片编辑"],["Claude Sonnet","Anthropic","视觉 · 文本"]].map((m,i)=><div key={m[0]} className="glass flex flex-wrap items-center justify-between gap-4 rounded-2xl p-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Sparkles/></span><div><b>{m[0]}</b><p className="text-xs text-slate-500">{m[1]} · {m[2]}</p></div></div><div className="flex items-center gap-3"><Badge variant="outline" className="border-emerald-400/20 text-emerald-300">可用</Badge><span className="text-xs text-slate-500">•••• {['8241','1963','4408'][i]}</span><Button variant="outline" size="sm">编辑</Button></div></div>)}</section><aside className="glass rounded-2xl p-5"><b>快速连接测试</b><p className="mt-1 text-xs text-slate-500">只进行低成本能力检测</p><label className="mt-5 block text-sm">Base URL<Input className="mt-2" defaultValue="https://api.example.com/v1"/></label><label className="mt-4 block text-sm">Model ID<Input className="mt-2" defaultValue="image-model-v1"/></label><label className="mt-4 block text-sm">API Key<Input className="mt-2" type="password" defaultValue="sk-demo-key"/></label><Button className="mt-5 w-full" onClick={()=>setTested(true)}>{tested?<><ShieldCheck/>连接正常</>:"检查连接与能力"}</Button></aside></div></div>}

function DatasetPanel(){const [ready,setReady]=useState(false);return <div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Data Cleaner</p><h1 className="mt-2 text-3xl font-semibold">Etsy 竞品数据清洗</h1><p className="mt-2 text-slate-400">兼容 Landrop CSV：归一化链接、店龄、销量、评论和热卖信号。</p><div className="mt-7 grid gap-4 lg:grid-cols-[380px_1fr]"><section className="glass rounded-2xl p-5"><label className="flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-white/15 bg-black/20 p-6 text-center"><input type="file" accept=".csv" className="hidden" onChange={()=>setReady(true)}/><Database className="size-9 text-primary"/><b className="mt-4">选择 Landrop CSV</b><span className="mt-1 text-xs text-slate-500">支持 UTF-8 BOM 与 13 个标准字段</span></label><Button className="mt-4 w-full" disabled={!ready} onClick={()=>setReady(true)}>开始清洗</Button></section><section className="glass rounded-2xl p-5"><div className="grid grid-cols-3 gap-3">{[["128","有效商品"],["32","独立店铺"],["18%","热卖占比"]].map(x=><div key={x[1]} className="rounded-xl bg-white/[.035] p-4"><b className="text-2xl">{ready?x[0]:"—"}</b><p className="mt-1 text-xs text-slate-500">{x[1]}</p></div>)}</div><div className="mt-5 overflow-hidden rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-white/5 text-slate-400"><tr><th className="p-3">店铺</th><th>店龄</th><th>销量</th><th>月均信号</th></tr></thead><tbody>{ready&&[["LinenNest","11 months","2.4k","218"],["SoftRoom","2 years","4.8k","200"],["CozyNorth","8 months","980","122"]].map(r=><tr key={r[0]} className="border-t"><td className="p-3">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td className="text-emerald-300">{r[3]}</td></tr>)}</tbody></table></div></section></div></div>}

function Placeholder({ view }: { view: StudioView }) {
  const data: Record<string,[string,string]>={"skill-editor":["创建商品 Skill","把每一张 SKU 的生成方法编排成可复用流程。"],"skill-market":["Skill 广场","发现其他卖家验证过的商品生成流程。"],"model-market":["模型广场","选择已验证的公共模型配置，只需填写自己的 API Key。"],datasets:["竞品数据清洗","导入 Landrop CSV，完成去重、标准化与选品信号分析。"],project:["法式亚麻被套 · 秋季系列","查看 SKU、生成结果、运行记录与 Etsy 上架包。"],profile:["Mira Studio","管理公开主页、已发布 Skill 和版本。"],models:["模型与 API 密钥","连接 OpenAI 兼容、Gemini、Claude 或声明式适配器。"],"skill-detail":["床品场景图 · 轻法式卧室","查看流程说明、版本、评价与试运行结果。"]}; const [title,sub]=data[view];
  return <div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">LoomLink</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">{title}</h1><p className="mt-2 text-slate-400">{sub}</p></div><Button><Plus/>新建</Button></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{skills.map((s,i)=><article key={s.title} className="glass overflow-hidden rounded-2xl"><div className={`h-28 bg-gradient-to-br ${s.color} p-4`}><Badge variant="secondary">{s.tag}</Badge><div className="mt-5 h-1.5 w-24 rounded-full bg-white/20"><div className="pulse-line h-full w-2/3 rounded-full bg-white/70"/></div></div><div className="p-4"><h2 className="font-medium">{view==="models"?["GPT Image 2","Gemini 3 Pro Image","Claude Sonnet","自定义 OpenAI 兼容"][i]:s.title}</h2><p className="mt-1 text-xs text-slate-500">{s.author}</p><div className="mt-4 flex items-center justify-between text-xs text-slate-400"><span className="flex items-center gap-1"><Star className="size-3.5 fill-amber-300 text-amber-300"/>{s.rating}</span><span>{s.runs} 次使用</span></div></div></article>)}</div></div>;
}

export function StudioApp({ view }: { view: StudioView }) { return <Shell>{view==="workspace"?<Workspace/>:view==="skill-editor"?<SkillEditor/>:view==="models"?<ModelsPanel/>:view==="datasets"?<DatasetPanel/>:<Placeholder view={view}/>}</Shell>; }
