"use client";
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { AppWindow, Boxes, CircleUserRound, Database, Layers3, Library, Menu, Search, Settings2, ShieldCheck, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Toaster } from "@/components/ui/sonner";
import { parseCsv, exportCsv } from "@/lib/csv";
import { cleanLandropRows } from "@/lib/landrop";
import { CloudSkillEditor } from "@/components/cloud-skill-editor";
import { ModelSettings } from "@/components/model-settings";
import { ProjectWorkspace } from "@/components/project-workspace";
import { ProjectPanel } from "@/components/project-panel";
import { MarketplacePanel } from "@/components/marketplace-panel";

export type StudioView="workspace"|"skill-editor"|"skill-market"|"model-market"|"datasets"|"project"|"profile"|"models"|"skill-detail";
const nav=[["/workspace","工作台",AppWindow],["/marketplace/skills","Skill 广场",Library],["/marketplace/models","模型广场",Boxes],["/datasets","数据清洗",Database],["/projects/demo","商品项目",Layers3],["/settings/models","模型设置",Settings2]] as const;
function Link({href,className,children,...props}:{href:string;className?:string;children:React.ReactNode;[key:string]:unknown}){return <a href={href} className={className} {...props}>{children}</a>}
function Brand(){return <Link href="/workspace" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary text-white"><Layers3 className="size-5"/></span><span><b className="block text-[15px] text-white">织链 LoomLink</b><small className="text-xs text-slate-400">Commerce Skill Studio</small></span></Link>}
function Shell({children}:{children:React.ReactNode}){
 const path=usePathname(),[mobile,setMobile]=useState(false),[q,setQ]=useState(""),[account,setAccount]=useState("账户");const closeRef=useRef<HTMLButtonElement>(null),openRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{fetch("/api/me").then(r=>r.json() as Promise<{ok:boolean;data?:{displayName:string}}>).then(j=>{if(j.ok&&j.data)setAccount(j.data.displayName)}).catch(()=>{})},[]);
 useEffect(()=>{if(!mobile)return;closeRef.current?.focus();const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMobile(false);setTimeout(()=>openRef.current?.focus())}};document.addEventListener("keydown",escape);const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",escape);document.body.style.overflow=previous}},[mobile]);
 const close=()=>{setMobile(false);setTimeout(()=>openRef.current?.focus())};
 return <div className="min-h-screen text-slate-100">{mobile&&<button aria-label="关闭导航菜单" className="fixed inset-0 z-[35] bg-black/60 lg:hidden" onClick={close}/>}<aside role={mobile?"dialog":undefined} aria-modal={mobile||undefined} aria-label="主导航" className={`fixed inset-y-0 left-0 z-40 w-[248px] border-r border-white/8 bg-[#090d13] px-4 py-5 transition-transform lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}><div className="flex items-center justify-between px-2"><Brand/><Button ref={closeRef} aria-label="关闭菜单" variant="ghost" size="icon-sm" className="lg:hidden" onClick={close}><X/></Button></div><nav className="mt-9 space-y-1">{nav.map(([href,label,Icon])=><Link key={href} href={href} onClick={()=>setMobile(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${path.startsWith(href.replace("/demo",""))?"bg-[#172234] text-white":"text-slate-300 hover:bg-white/5 hover:text-white"}`}><Icon className="size-[18px]"/>{label}</Link>)}</nav><div className="absolute inset-x-4 bottom-5 rounded-2xl border border-white/8 bg-white/[.025] p-3"><div className="flex items-center gap-2 text-sm text-slate-300"><ShieldCheck className="size-4 text-emerald-400"/>账号数据独立保存</div><p className="mt-2 text-xs text-slate-400">API Key 仅在服务端加密存储</p></div></aside><div className="lg:pl-[248px]"><header className="sticky top-0 z-30 flex h-16 items-center gap-4 border-b border-white/8 bg-[#080b10]/90 px-4 backdrop-blur-xl md:px-7"><Button ref={openRef} aria-label="打开菜单" aria-expanded={mobile} variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></Button><form className="relative max-w-xl flex-1" onSubmit={e=>{e.preventDefault();if(q.trim())window.location.assign(`/marketplace/skills?q=${encodeURIComponent(q)}`)}}><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={q} onChange={e=>setQ(e.target.value)} className="h-10 border-white/10 bg-white/[.04] pl-9" placeholder="搜索公开 Skill…"/></form><Badge variant="outline" className="hidden border-emerald-400/20 bg-emerald-400/5 text-emerald-200 sm:flex">云端数据已接通</Badge><Link aria-label={`个人主页：${account}`} title={account} href="/profile/me" className="grid size-10 place-items-center rounded-full border border-white/10 bg-[#18243a]"><CircleUserRound className="size-5"/></Link></header><main className="grid-fade min-h-[calc(100vh-4rem)] p-4 md:p-7">{children}</main></div><Toaster richColors position="top-center" offset={72}/></div>
}

function DatasetPanel(){const[file,setFile]=useState<File|null>(null),[rows,setRows]=useState<Record<string,unknown>[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[removed,setRemoved]=useState(0);async function clean(){if(!file)return;setBusy(true);setError("");setRows([]);try{if(file.size>10*1024*1024)throw new Error("CSV 不能超过 10MB");const input=parseCsv(await file.text());if(!input.length)throw new Error("CSV 没有数据记录");if(!("listing_id" in input[0])&&!("listing_url" in input[0]))throw new Error("缺少 listing_id 或 listing_url 列");const cleaned=cleanLandropRows(input);setRows(cleaned);setRemoved(input.length-cleaned.length);if(!cleaned.length)throw new Error("没有有效的 Etsy 商品记录")}catch(e){setError(e instanceof Error?e.message:"文件读取失败")}finally{setBusy(false)}}const headers=rows.length?Object.keys(rows[0]):[];return <div className="mx-auto max-w-6xl"><h1 className="text-3xl font-semibold">Etsy 竞品数据清洗</h1><p className="my-4 text-slate-300">按商品 ID 去重，规范 Etsy 链接、店龄和销量。缺失数值保留为空。</p><section className="glass space-y-4 rounded-2xl p-5"><label className="block text-sm">导入 Landrop CSV<input aria-label="导入 Landrop CSV" className="mt-2 block" type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]||null);setRows([]);setError("")}}/></label><Button disabled={!file||busy} onClick={clean}>{busy?"清洗中…":"开始清洗"}</Button>{error&&<p role="alert" className="text-red-200">{error}</p>}{!!rows.length&&<><p role="status">{rows.length} 条有效记录 · 移除 {removed} 条重复或无效记录 · {new Set(rows.map(r=>r.shop_name).filter(Boolean)).size} 家店铺</p><Button onClick={()=>{const url=URL.createObjectURL(new Blob([exportCsv(rows)],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="cleaned-etsy-data.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>下载 CSV</Button><div className="overflow-auto"><table className="w-full text-sm"><caption className="sr-only">清洗后的 Etsy 竞品数据，预览前 100 条</caption><thead><tr>{headers.map(h=><th className="p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,100).map((r,i)=><tr key={i}>{headers.map(h=><td className="whitespace-pre-wrap border-t p-3" key={h}>{r[h]==null?"—":String(r[h])}</td>)}</tr>)}</tbody></table></div><p className="text-sm text-slate-300">预览前 100 条；下载包含全部清洗记录。移动端可左右滚动表格。</p></>}</section></div>}

export function StudioApp({view}:{view:StudioView}){return <Shell>{view==="workspace"?<ProjectWorkspace/>:view==="skill-editor"?<CloudSkillEditor/>:view==="models"?<ModelSettings/>:view==="datasets"?<DatasetPanel/>:view==="project"?<ProjectPanel/>:<MarketplacePanel view={view}/>}</Shell>}
